---
title: "DLS-Quiz"
author: "Yang Ge"
date: "1/16/2018"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course 4

## Week 2

1. Question 1 (D)

Which of the following do you typically see as you move to deeper layers in a ConvNet?

A. nH and nW decreases, while nC also decreases

B. nH and nW increases, while nC also increases

C. nH and nW increases, while nC decreases

D. nH and nW decrease, while nC increases

2. Question 2 (A, D)

Which of the following do you typically see in a ConvNet? (Check all that apply.)

A. Multiple CONV layers followed by a POOL layer

B. Multiple POOL layers followed by a CONV layer

C. FC layers in the last few layers

D. FC layers in the first few layers

3. False

In order to be able to build very deep networks, we usually only use pooling layers to downsize the height/width of the activation volumes while convolutions are used with “valid” padding. Otherwise, we would downsize the input of the model too quickly.

True

False

4. False

Training a deeper network (for example, adding additional layers to the network) allows the network to fit more complex functions and thus almost always results in lower training error. For this question, assume we’re referring to “plain” networks.

True

False

5.  a[l] and 0, respectively

The following equation captures the computation in a ResNet block. What goes into the two blanks above?

$$
a^{[l+2]} = g(W^{[l+2]}g(W^{[l+1]}a^{[l]}+b^{[l+1]})+b^{[l+2]}+ ?)+?
$$

A. 0 and a[l], respectively

B. a[l] and 0, respectively

C. z[l] and a[l], respectively

D. 0 and z[l+1], respectively

6. (A)(B)(D) wrong (A)(B) correct

Which ones of the following statements on Residual Networks are true? (Check all that apply.)

A. The skip-connection makes it easy for the network to learn an identity mapping between the input and the output within the ResNet block.

B. Using a skip-connection helps the gradient to backpropagate and thus helps you to train deeper networks

C. A ResNet with L layers would have on the order of L2 skip connections in total.

D. The skip-connections compute a complex non-linear function of the input to pass to a deeper layer in the network.

7. C

Suppose you have an input volume of dimension 64x64x16. How many parameters would a single 1x1 convolutional filter have (including the bias)?

A. 1

B. 2

C. 17

D. 4097

8. (B)(D)

Suppose you have an input volume of dimension nH x nW x nC. Which of the following statements you agree with? (Assume that “1x1 convolutional layer” below always uses a stride of 1 and no padding.)


A. You can use a pooling layer to reduce nH, nW, and nC.

B. You can use a pooling layer to reduce nH, nW, but not nC.

C. You can use a 1x1 convolutional layer to reduce nH, nW, and nC.

D. You can use a 1x1 convolutional layer to reduce nC but not nH, nW.

9. (A)(C)

Which ones of the following statements on Inception Networks are true? (Check all that apply.)

A. A single inception block allows the network to use a combination of 1x1, 3x3, 5x5 convolutions and pooling.

B. Making an inception network deeper (by stacking more inception blocks together) should not hurt training set performance.

C. Inception blocks usually use 1x1 convolutions to reduce the input data volume’s size before applying 3x3 and 5x5 convolutions.

D. Inception networks incorporates a variety of network architectures (similar to dropout, which randomly chooses a network architecture on each step) and thus has a similar regularizing effect as dropout.

10. (C)(D)

Which of the following are common reasons for using open-source implementations of ConvNets (both the model and/or weights)? Check all that apply.

A. The same techniques for winning computer vision competitions, such as using multiple crops at test time, are widely used in practical deployments (or production system deployments) of ConvNets.

B. A model trained for one computer vision task can usually be used to perform data augmentation even for a different computer vision task.

C. Parameters trained for one computer vision task are often useful as pretraining for other computer vision tasks.

D. It is a convenient way to get working an implementation of a complex ConvNet architecture.

## Week 3

1. A

You are building a 3-class object classification and localization algorithm. The classes are: pedestrian (c=1), car (c=2), motorcycle (c=3). What would be the label for the following image? Recall $y=[p_c, b_x, b_y, b_h, b_w, c_1, c_2, c_3]$

A. $y=[1,0.3,0.7,0.3,0.3,0,1,0]$
B. $y=[1,0.7,0.5,0.3,0.3,0,1,0]$
C. $y=[1,0.3,0.7,0.5,0.5,0,1,0]$
D. $y=[1,0.3,0.7,0.5,0.5,1,0,0]$
E. $y=[0,0.2,0.4,0.5,0.5,0,1,0]$

2. C 

Continuing from the previous problem, what should y be for the image below? Remember that “?” means “don’t care”, which means that the neural network loss function won’t care what the neural network gives for that component of the output. As before, $y=[p_c, b_x, b_y, b_h, b_w, c_1, c_2, c_3]$

A. $y=[?,?,?,?,?,?,?,?]$
B. $y=[0,?,?,?,?,0,0,0]$
C. $y=[0,?,?,?,?,?,?,?]$
D. $y=[1,?,?,?,?,0,0,0]$
E. $y=[1,?,?,?,?,?,?,?]$

3. B

You are working on a factory automation task. Your system will see a can of soft-drink coming down a conveyor belt, and you want it to take a picture and decide whether (i) there is a soft-drink can in the image, and if so (ii) its bounding box. Since the soft-drink can is round, the bounding box is always square, and the soft drink can always appears as the same size in the image. There is at most one soft drink can in each image. Here’re some typical images in your training set:

What is the most appropriate set of output units for your neural network?

A. Logistic unit (for classifying if there is a soft-drink can in the image)
B. Logistic unit, bx and by
C. Logistic unit, bx, by, bh (since bw = bh)
D. Logistic unit, bx, by, bh, bw

4. B

If you build a neural network that inputs a picture of a person’s face and outputs N landmarks on the face (assume the input image always contains exactly one face), how many output units will the network have?

A. N
B. 2N
C. 3N
D. $N^2$

5. False

When training one of the object detection systems described in lecture, you need a training set that contains many pictures of the object(s) you wish to detect. However, bounding boxes do not need to be provided in the training set, since the algorithm can learn to detect the objects by itself.

A. True
B. False

6. False

Suppose you are applying a sliding windows classifier (non-convolutional implementation). Increasing the stride would tend to increase accuracy, but decrease computational cost.

A. True
B. False

7. True

In the YOLO algorithm, at training time, only one cell ---the one containing the center/midpoint of an object--- is responsible for detecting this object.

A. True
B. False

8. 1/9

What is the IoU between these two boxes? The upper-left box is 2x2, and the lower-right box is 2x3. The overlapping region is 1x1.

A. 1/6
B. 1/9
C. 1/10
D. None of the above

9. 1st: 4 2nd: 5, two tree boxes should be both there

Suppose you run non-max suppression on the predicted boxes above. The parameters you use for non-max suppression are that boxes with probability ≤ 0.4 are discarded, and the IoU threshold for deciding if two boxes overlap is 0.5. How many boxes will remain after non-max suppression?

A. 3
B. 4
C. 5
D. 6
E. 7

10. 1st try: 19x19x(5x20) 2nd try 19x19x(5x25)

Suppose you are using YOLO on a 19x19 grid, on a detection problem with 20 classes, and with 5 anchor boxes. During training, for each image you will need to construct an output volume y as the target value for the neural network; this corresponds to the last layer of the neural network. (y may include some “?”, or “don’t cares”). What is the dimension of this output volume?

A. 19x19x(20x25)
B. 19x19x(25x20)
C. 19x19x(5x25)
D. 19x19x(5x20)

## Week 3

1. True

Face verification requires comparing a new picture against one person’s face, whereas face recognition requires comparing a new picture against K person’s faces.

2. (B)(C)

Why do we learn a function $d(img1,img2)$ for face verification? (Select all that apply.)

A. Given how few images we have per person, we need to apply transfer learning.
B. We need to solve a one-shot learning problm
C. This allows us to learn to recognize a new person given just a single image of that person.
D. This allows us to learn to predict a person’s identity using a softmax output unit, where the number of classes equals the number of persons in the database plus 1 (for the final “not in database” class).

3. False

In order to train the parameters of a face recognition system, it would be reasonable to use a training set comprising 100,000 pictures of 100,000 different persons.

4. $L(A, P, N) = \max (||f(A) - f(P)||^2 - ||f(A) - f(N)||^2 + \alpha, 0)$

Which of the following is a correct definition of the triplet loss? Consider that $α>0$.
(We encourage you to figure out the answer from first principles, rather than just refer to the lecture.)

5. True

Consider the following Siamese network architecture:

The upper and lower neural networks have different input images, but have exactly the same parameters.

6. True

You train a ConvNet on a dataset with 100 different classes. You wonder if you can find a hidden unit which responds strongly to pictures of cats. (I.e., a neuron so that, of all the input/training images that strongly activate that neuron, the majority are cat pictures.) You are more likely to find this unit in layer 4 of the network than in layer 1.

7. 1st True, 2nd False

Neural style transfer is trained as a supervised learning task in which the goal is to input two images (x), and train a network to output a new, synthesized image (y).

8. True

In the deeper layers of a ConvNet, each channel corresponds to a different feature detector. The style matrix G[l] measures the degree to which the activations of different feature detectors in layer l vary (or correlate) together with each other.

9. 1st C, 2nd D

In neural style transfer, what is updated in each iteration of the optimization algorithm?

A. The regularization parameters
B. The pixel values of the content image C
C. The neural network parameters
D. The pixel values of the generated image G

10. 30x30x30x32

You are working with 3D data. You are building a network layer whose input volume has size 32x32x32x16 (this volume has 16 channels), and applies convolutions with 32 filters of dimension 3x3x3 (no padding, stride 1). What is the resulting output volume?

A. 30x30x30x16
B. Undefined: This convolution step is impossible and cannot be performed because the dimensions specified don’t match up.
C. 30x30x30x32