---
title: "Notes-on-Understanding-Analysis"
author: "Yang Ge"
date: "9/28/2017"
output:
  html_document:
    keep_md: false
    toc: true
---

# Chapter 1
## section 1.3 The Axiom of Completeness

* **_1.3.0 Axiom of Completeness_:** Every non empty set of real numbers that is bounded above has a least upper bound.

* **_1.3.1 Definition of LB and UB_:** $A \subseteq R$ is bounded above if there exists $b$,
such that $a \le b$ for all $a \in A$. Similar for lower bound.

* **_Lemma 1.3.8_** Assume $s \in R$ is an upper bound for a set $A \$

### Exercises

* **_Exercise 1.3.3_**

(a) For any $a \in A$, a is an upper bound of $B$, thus $\sup B <= a$. Thus $\sup B$ is a lower
bound of $A$. For any lower bound of A $b \in B, b <= \sup B$, thus $\sup B = \inf A$.
(b) The greatest lower bound can be deduced from (a)

* **_Exercise 1.3.4_**

(a) It's the $\max \sup(A_k)$.
(b) It cannot be generalized to infinite cases. Let $A_n = \{x|x \le n\}$, $\cup_{i=1}^\infty A_n = R$. It's not even bounded above.

* **_Exercise 1.3.6_**

(a) let $c \in A+B$, then $c = a+b$ for some $a \in A, b \in B$.
    Then $a \le s, b \le t$, then $a+b \le s+t$. $s+t$ is an upper bound of $A+B$.
(b) First, we show $u-a$ is a upper bound of $B$.
If $b \in B$, then $a + b \leq u$, then
    $b \leq u-a$ for $b \in B$. Then $u-a$ is an upper bound of $B$. We have $t \leq u-a$
(c) Next we show $u-t$ is an upper bound of $A$. This is because for all $a \in A$,
we have $t \leq u-a$, it means $a \leq u - t$, then $r \leq u-t$. So $r+t \leq u$.
(d) For any $\epsilon > 0$, We can find $a \in A, a > r - \epsilon / 2$ and $b \in B, b > s - \epsilon / 2$, so $a+b \in A+B$ and $a+b > r+s-\epsilon$.
    
* **_Exercise 1.3.7_**

1. $a$ is an upper bound of $A$, then $a \ge \sup A$.
2. On the other hand, $a \in A$, so $a \le \sup A$.
3. Together we have $a = \sup A$.

* **_Exercise 1.3.8_**

(a) 0, when $m = 1, n \rightarrow \inf$. 1, when $m = n-1, n \rightarrow \inf$.
(b) -1, +1
(c) 1/4, 1/3
(d) 0, 1

* **_Exercise 1.3.9_**

(a) Assume $\epsilon = \sup B - \sup A > 0$, according to lemma 1.3.8, there is $b \in B$ such
    that $b > \sup B - \epsilon = \sup A$. So $b$ is an upper bound of $A$.
(b) Let $A = [0,1], B=(0,1)$, then $\sup A = \sup B = 1$. If $b \in B$ is an upper bound of $A$,
    then $b \ge 1$, then $b \notin B$.

* **_Exercise 1.3.10 (Cut Property)_**

(a) Let $c = \sup A$. Then for $x \in A, x <= c$. For $b \in B$, because $a < b, \forall a \in A$,
    Then $b$ is an upper bound of $A$, therefore, $c \le b$.
(b) The other way. Let $B$ be the set of all upper bounds of $A$. $c$ is the cut, then $c \ge a$
    for all $a \in A$. Then $c$ is an upper bound of $A$. Let $b$ be an upper bound, then $b \in B$. Then $c \le b$, then $c = \sup A$.
(c) Let $A = \{a|a^2<2\}, B = \{b|b^2>2\}$.

* **_Exercise 1.3.11_**

(a) True. For $a \in A$, we have $a \in B$, then $a <= \sup B$. So $\sup B$ is an upper bound
    of $A$. Therefore $\sup A \le \sup B$.
(b) True. Let $c = (\sup A + \inf B) / 2$, the $\inf B > c > \sup A$. So
$$
a \le \sup A < c < \inf B \le b
$$

(c) False. Let $A = \{a| a \in \mathbb{Q}, a^2 < 2\}$, $B = \{b| b \in \mathbb{Q}, b^2 > 2\}$ and
    $c = 2$. Then $\sup A = \inf B = \sqrt{2}$ .

## section 1.4 The Consequence of the Axiom of Completeness

* **_1.4.1 Nested Interval Property_:** $I_n = [a_n, b_n]$ and $I_n \supseteq I_{n+1}$, then

$$
\displaystyle\cap_{i=1}^\infty I_i \neq \emptyset.
$$

* **_proof_:** Let $A = \{a_n\},B=\{b_n\}$. Let $x = \sup A$. Since every $b_n$ is an upper
bound of $A$, we have $x \le b_n$. Then $a_n \le x \le b_n$.
For every $n$, $x \in I_n$.

* **_1.4.2 Archimedean Property_:** 
(i) $x \in R$, then there exists $n \in N, n > x$.
(ii) $y > 0$, then there exists $n \in N, 1/n < y$.

* **_proof_:**
(i) Assume $N$ is bounded above, and $\alpha = \sup N$. Then there exists $n > \alpha -1$.
Then $n + 1 > \alpha$. We got a contradiction.
(ii) Let $x = 1/y$, and we find $n > x$, then $1/n < 1/x = y$.

* **_1.4.3 Density of Q in R_:** $a < b$, then exist rational number $r$, s.t. $a < r < b$.

(i) from 1.4.2, let $1/n < b-a$. Choose $m > an >= m-1$, then $a < m/n = (m-1)/n + 1/n \le a+1/n < b$.

* **_1.4.5 squre root in R_:** there exists $\alpha \in R$, such that $\alpha^2=2$.

* **_Exercise 1.4.1_** 

(a) Let $a = \frac{p}{q}, b=\frac{r}{s}$, then $a+b= \frac{ps+qr}{qs} \in \mathbb{Q}$.
(b) Let $b = a+t$, then $t = b + (-a)$. If $b \in \mathbb{Q}$, then $t \in \mathbb{Q}$,
    we have contradiction.
(c) Let $s = 2 + \sqrt{2}, t = 2-\sqrt{2},s+t=4,st=2$. $\mathbb{I}$ is not closed
    under addition and multiplication.

* **_Exercise 1.4.2_**

(a) First to prove $s$ is an upper bound of $A$. Let $a \in A$, if $a > s$, let $\epsilon = a - s > 0$.
Based on Archimedean Property, we can fine $n, s.t. 1/n < \epsilon$, then $s + 1/n < s + \epsilon=a$.
We have a contradiction.
(b) Second, if $s' < s$ is an upper bound, then $\epsilon = s - s'>0$, again we can find
$n, s.t. 1/n < \epsilon$, so $s'+1/n<s'+\epsilon=s$, so $s'<s-1/n$. Since $s-1/n$ is not an upper
bound of $A$, $s'$ cannot be as well. We have a contradiction.

* **_Exercise 1.4.3_**

(a) Assume $x \in \cap_{n=1}^{\infty}(0, 1/n)$. First $x \in (0,1)$, so $x > 0$.
Then according to Archimedean Property, we have $n, x > 1/n$, so $x \notin (0, 1/n)$.
We have a contradiction.

* **_Exercise 1.4.4_**

(a) Let $x \in [a,b] \cap \mathbb{Q}$, then $x \in [a,b]$, then $x \le b$, b is an upper bound.
(b) Let $a < c < b$, then according to 1.4.3, there exists $r \in Q$, s.t. $c < r < b$.
    Then $a < c < r < b$, so $r \in [a,b] \cap \mathbb{Q}$. $c$ is not an upper bound of $T$.
    Then $b = \sup T$.
    
* **_Exercise 1.4.5_** Given any real number $a < b$, there exists an irrational number $r$, such
that $a < r < b$.

(a) If a is irrational, we can find a rational number $a'$ such that $a < a' < b$. Same argument holds
for $b$. So we can assume $a, b$ are all rational.
(b) Now we can find $n$, s.t. $1/n < (b-a)/2$. Then we have $an < an + \sqrt{2} < an+2 < bn$.
Then we have $a < a + \sqrt{2}/n < b$. Since $a, 1/n$ are all rational, then $a + \sqrt{2}/n$
is irrational.
(c) A better proof: $a-\sqrt{2} < r < b-\sqrt{2}$.

* **_Exercise 1.4.6_**

(a) not dense
(b) dense
(c) Not dense. We can't find $p,q$ such $0 < p/q < 1/10$, which means $10|p| < q$

* **_Exercise 1.4.7_**

(a) $T = \{t \in R:  t^2 < 2\}$, $\alpha = \sup T$. Assume $\alpha ^ 2 > 2$, then
    $(\alpha - 1/n)^2 = \alpha^2 - 2\alpha/n + 1/n^2 > \alpha^2 - 2\alpha/n > 2$,
    if $n$ is big enough.
(b) On the other hand, we can find $t \in T$, such that $t > \alpha - 1/n$, so
    $t^2 > (\alpha - 1/n)^2 > 2$. We have a contradiction.

* **_Exercise 1.4.8_**

(a) Example: $A = \{r, r < 2, r \text{ is rational}\}$, $B = \{r, r < 2, r \text{ is irrational}\}$.
(b) Example: $J_i = \{ x : (-1/i, 1/i) \}$. We see $0 \in J_i$ and ${0} = \cap_{n=1}^{\infty} J_i$.
(c) Example: $L_i = [i, \infty)$
(d) Impossible: let $L_i = \cap_1^i J_i$, they are closed non-empty set, and they are nested.
    So based on "Nested Interval Property", $\cap_{n=1}^{\infty} J_i = \cap_{n=1}^{\infty} L_i$.

# Chapter 2 Sequences and Series

The crucial question is whether or not properties of addition and equality that are well understood for finite sums remain valid when applied to infinite objects such as equation.

## 2.2 The Limit of a Sequence

**_Definition 2.2.1_**. A sequence is a function whose domain is N.

**_Definition 2.2.3 Convergence of a Sequence)_**. A sequence $(a_n)$ converges to a real number $a$ if, for every positive number $ε$, there exists an $N ∈ \mathbb{N}$ such that whenever $n ≥ N$ it follows that $|a_n − a| < ε$.

**_Definition 2.2.4._** Given a real number $a ∈ R$ and a positive number $ε > 0$, the set
$$
V_{ε}(a)=\{x \in \mathbb{R} : |x-a| < ε\}
$$
is called the ε-neighborhood of $a$.

***Definition 2.2.3B (Convergence of a Sequence: Topological Version).*** A sequence $(a_n)$ converges to a if, given any ε-neighborhood $V_ε(a)$ of $a$, there exists a point in the sequence after which all of the terms are in $V_ε(a)$. In other words, every ε-neighborhood contains all but a finite number of the terms of $(a_n)$.

### Quantifiers

## 2.4 The Monotone Convergence Theorem and a First Look at Infinite Series

***Definition 2.4.1.*** A sequence $(a_{n})$ is *increasing* if $a_{n} \le a_{n+1}$
for all $n\in \mathbb{N}$ and *decreasing* if $a_{n} \ge a_{n+1}$ for all $n\in \mathbb{N}$. A sequence is *monotone* if it is either increasing or decreasing.

***Theorem 2.4.2 (Monotone Convergence Theorem).*** *If a sequence is monotone and bounded, then it converges.*

*Proof*: Let $s = \sup \{ a_{n} : n \in \mathbb{N} \}$.

***Definition 2.4.3 (Convergence of a Series).*** Let $(b_{n})$ be a sequence. An *infinite sequence* is a formal expression of the form

$$
\sum_{n=1}^{\infty} b_n = b_1 + b_2 + \cdots
$$

We define the corresponding *sequence of partial sums* ($s_m$) by

$$
s_m = b_1 + b_2 + \cdots + b_m,
$$

and say that the series $\sum_{n=1}^{\infty} b_n$ converges to $B$, if the sequence ($s_m$) converges to $B$. In this case, we write $\sum_{n=1}^{\infty} b_n = B$.

***Example 2.4.4.*** Consider
$$
\sum_{n=1}^{\infty} \frac{1}{n^2}
$$
We have
$$
s_m < (2 - \frac{1}{m}) < 2
$$
So we know it will converge.

***Example 2.4.5.*** Consider the so-called *harmonic series*
$$
\sum_{n=1}^{\infty} \frac{1}{n}
$$
We have
$$
s_{2^k} > 1 + k\left(\frac{1}{2}\right)
$$
***Theorem 2.4.6 (Cauchy Condensation Test).*** Suppose $(b_n)$ is decreasing and satisfies $(b_n) \ge 0$ for all $n\in \mathbb{N}$. Then, the series $\sum_{n=1}^{\infty} (b_n)$ converges if and only if the following series converges.

$$
\sum_{n=0}^{\infty} 2^n b_{2^n}
=
b_1 + 2 b_2 + 4 b_4 + \cdots
$$
***Corollary 2.4.7.*** The series $\sum_{n=1}^{\infty} 1 / n^p$ converges if and only if $p > 1$.

### Exercises

***Exercise 2.4.1.***

(a) Prove that the sequence defined by $x_1 = 3$ and

$$
x_{n+1} = \frac{1}{4-x_n}
$$

converges.

Proof: $x1 = 3, x_2 = 1, x_3 = 1/3, x_4 = 3/11$, assume $x_n < x_{n-1}$, then

$$
x_{n+1} = \frac{1}{4-x_n} < \frac{1}{4-x_{n-1}} < x_n
$$

And $x_n > 0$, so $(x_n)$ is monotonous decreasing and bounded. So it converges.

(b) Now that we know $\lim x_n$ exists, explain why $\lim x_{n+1}$ must also exist and equal the same value.

Proof: $x_{n+1}$ is also monotonous decreasing and bounded.

(c)

$$
x(4-x) = 1 \\
x^2 - 4x+1=0 \\
x = \frac{4 \pm \sqrt{12}}{2}
$$

***Exercise 2.4.2.***

(a) Consider the recursively defined sequence $y_1 = 1$,

$$
y_{n+1} = 3 - y_n
$$

and set $y = \lim y_n$. Because $(y_n)$ and $(y_{n+1})$ have the same limit, taking the limit across the recursive equation gives $y = 3-y$. Solving for
$y$, we conclude $y = \lim y_n = 3/2$. What is wrong with this argument?

Solution:

$$
y_n = 
\begin{cases}
1 & \quad \text{if } n \text{ is even} \\
2 & \quad \text{if } n \text{ is odd}
\end{cases}
$$
So $\lim y_n$ does not exist.

(b) This time set $y_1 = 1$ and $y_{n+1} = 3− \frac{1}{y_n}$. Can the strategy in (a) be applied $y_n$ to compute the limit of this sequence?

Solution: yes. $3 > y_2 > y_1 \ge 1$, and assume $3 > y_{n} > y_{n-1} \ge 1$, then 

$$
3 > 3 - \frac{1}{y_n} > 3 - \frac{1}{y_{n-1}} = y_n \ge 1
$$

So

$$
3 > y_{n+1} > y_n \ge 1
$$

so $(y_n)$ is monotonous increasing and bounded.

***Exercise 2.4.3.***

(a) Show that 

$$
\sqrt{2}, \sqrt{2+\sqrt{2}}, \sqrt{2+\sqrt{2+\sqrt{2}}}, \dots
$$
converges and find the limit.

Proof: let $b_1 = \sqrt{2}, b_2 = \sqrt{2+\sqrt{2}}$, then in general,
we have $b_{n+1} = \sqrt{2 + b_n}$. Because $b_2 > b_1$, and assume $b_n > b_{n-1}$, then $b_{n+1} = \sqrt{2 + b_n} > \sqrt{2+b_{n-1}} = b_n$.
So we prove this sequence is monotonous increasing.

Next, because $b_1 < 2$, and assume $b_n < 2$. Then we have $b_{n+1} = \sqrt{2+ b_n} < \sqrt{2+2} = 2$, so $b_n < 2, \forall n$. So this sequence is bounded.
So it converges.

Finally,

$$
b_{n+1}-2 = \sqrt{2+b_n}-2 =
\frac{2+b_n-4}{\sqrt{2+b_n}+2} =\\
\frac{b_n-2}{\sqrt{2+b_n}+2} < \\
\frac{b_n-2}{2} < \frac{b_1 - 2}{2^{n-1}}
$$
So we have $\lim b_n = 2$

(b) Does the sequence

$$
\sqrt{2}, \sqrt{2\sqrt{2}}, \sqrt{2\sqrt{2\sqrt{2}}}, \dots
$$
converge? If so, find the limit.

Proof: 

First, we show it's monotonous increasing. let $b1 = \sqrt{2}, b_2 = \sqrt{2\sqrt{2}}, b_3 = \sqrt{2\sqrt{2\sqrt{2}}}$, then in general, we have
$b_{n+1} = \sqrt{2b_n}$, because $b_2 > b_1$, and assume $b_n > b_{n-1}$, then
$b_{n+1} = \sqrt{2b_n} > \sqrt{2b_{n-1}} = b_n$.

Next we show it's upper bounded by 2. $b_1 < 2$ and assume $b_n < 2$, then
$b_{n+1} = \sqrt{2b_n} < \sqrt{2\times2} = 2$.

Finally, we show

$$
2 - b_{n+1} = 2 - \sqrt{2b_n} =\\
\frac{4-2b_n}{2+\sqrt{2b_n}} = \\
\frac{2-b_n}{1+\sqrt{\frac{b_n}{2}}} < \\
\frac{2-b_n}{1+\sqrt{\frac{b_1}{2}}} < \\
\frac{2-b_n}{1+\sqrt{\frac{1}{2}}} < \\
\frac{2-b_1}{(1+\sqrt{\frac{1}{2}})^{n-1}} \rightarrow 0
$$

***Exercise 2.4.4.*** 

(a) In Section 1.4 we used the Axiom of Completeness (AoC) to prove the Archimedean Property of $\mathbb{R}$ (Theorem 1.4.2). Show that the Monotone Convergence Theorem can also be used to prove the Archimedean Property without making any use of AoC.

**_1.4.2 Archimedean Property_:** 
(i) $x \in R$, then there exists $n \in N, n > x$.
(ii) $y > 0$, then there exists $n \in N, 1/n < y$.

Proof: Assume $\mathbb{N}$ is bounded, then we can assume $\lim n = a$.
Now $a-1$ is not a upper bound for $\mathbb{N}$, we can find $n$, such that
$n > a-1$, than means $n+1 > a$. We have an contradiction.

(b) Use the Monotone Convergence Theorem to supply a proof for the Nested Interval Property (Theorem 1.4.1) that doesn’t make use of AoC.

* **_1.4.1 Nested Interval Property_:** $I_n = [a_n, b_n]$ and $I_n \supseteq I_{n+1}$, then

$$
\displaystyle\cap_{i=1}^\infty I_i \neq \emptyset.
$$

Proof: $\{a_n\}$ is monotonous increasing and bounded, so we can assume $\lim a_n = a$. If $b_m < a$, then we can find $n$, such that $n > m$ and $b_m < a_n < b_n < a$. However, $\{b_n\}$ is monotonous decreasing, so we must have $b_n <= b_m$, then we have a contradiction. Therefore, $b_m >= a, \forall m$.
So $a \in I_i, \forall i$.

***Exercise 2.4.5 (Calculating Square Roots).*** Let $x_1 = 2$, and define

$$
x_{n+1} = \frac{1}{2}(x_n + \frac{2}{x_n})
$$

(a) Show that $x^2$ is always greater than or equal to 2, and then use this to
prove that $x_{n} − x_{n+1} ≥ 0$. Conclude that $\lim x_n = \sqrt{2}$.

Proof: 

$$
x_{n+1}^2 - 2 = \frac{1}{2}(x_n + \frac{2}{x_n})^2 - 2
= \frac{1}{4}(x_n^2 + 4 + \frac{4}{x_n^2}) - 2
\ge \frac{1}{x_n^2} 
\ge 0
$$
$$
x_{n} − x_{n+1} = \frac{1}{2}(x_n - \frac{2}{x_n}) \ge 0
$$

$$
x_{n+1} - \sqrt{2} = \frac{1}{2}(x_n-2\sqrt{2}+\frac{2}{x_n})
= \frac{1}{2} (\sqrt{x_n} - \frac{\sqrt{2}}{\sqrt{x_n}})^2\\
= \frac{1}{2} \frac{(x_n - \sqrt{2})^2}{x_n} \\
= \frac{1}{2} (x_n - \sqrt{2}) \frac{x_n - \sqrt{2}}{x_n} \\
\le \frac{1}{2} (x_n - \sqrt{2}) \le \frac{1}{2^{n-1}} (2 - \sqrt{2})
$$

So $\lim x_n = \sqrt{2}$.

***Exercise 2.4.6. (Arithmetic–Geometric Mean). *** (a) Explain why $\sqrt{xy} \le (x+y)/2$ for any two positive real numbers x and y.

Proof:

$$
x + y - 2\sqrt{xy} = (\sqrt{x} - \sqrt{y})^2 \ge 0
$$
So $\sqrt{xy} \le (x+y)/2$.

(b) Now let $0≤ x_1 ≤ y_1$ and define

$$
x_{n+1} = \sqrt{x_ny_n} \quad \text{and} \quad y_{n+1} = \frac{x_n+y_n}{2}
$$

Show $lim x_n$ and $lim y_n$ both exist and are equal.

Proof: $x_{n+1} = \sqrt{x_ny_n} \ge \sqrt{x_nx_n} = x_n$ and 
$y_{n+1} \le \frac{y_n+y_n}{2} = y_n$, so $x_n$ is monotonous increasing,
and $y_n$ is monotonous decreasing. And they are bounded.
So $lim x_n$ and $lim y_n$ both exist.

$$
y_{n+1} - x_{n+1} = \frac{1}{2}(\sqrt{y_n} - \sqrt{x_n})^2 \le
\frac{1}{2}(\sqrt{y_n} - \sqrt{x_n})(\sqrt{y_n} + \sqrt{x_n}) =
\frac{y_n - x_n}{2} \le \frac{y_1 - x_1}{2^{n-1}}
$$

So $\lim y_n - \lim x_n = 0$.

***Exercise 2.4.7. (Limit Superior). *** Let $(a_{n})$ be a bounded sequence.

(a) Prove that the sequence defined by $y_n = \sup \{a_k : k ≥ n\}$ converges.

Proof: $y_n$ is a monotonous decreasing. And $y_n \ge \inf \{(a_n)\}$, so
$y_n$ is bounded. So $y_n$ converges.

(b) The limit superior of $(a_{n})$, or $\lim \sup a_n$ , is defined by

$$
\lim \sup a_n = \lim y_n
$$

where $y_n$ is the sequence from part (a) of this exercise. Provide a reason- able definition for $\lim \inf a_n$ and briefly explain why it always exists for any bounded sequence.

Solution: let $x_n = \inf \{a_k : k ≥ n\}$, then define:

$$
\lim \inf a_n = \lim x_n
$$

(c) Prove that $\lim \inf a_n ≤ \lim \sup a_n$ for every bounded sequence, and give an example of a sequence for which the inequality is strict.

Proof: Because $x_n \le y_n$, according to Theorem 2.3.4 (Order Limit Theorem),
we have $\lim \inf a_n ≤ \lim \sup a_n$. Consider the following sequence

$$
a_n = 
\begin{cases}
0 & \quad \text{if } n \text{ is even} \\
1 & \quad \text{if } n \text{ is odd}
\end{cases}
$$

(d) Show that $\lim \inf a_n = \lim \sup a_n$ if and only if $\lim a_n$ exists. In this case, all three share the same value.

Proof: **only if**: let $\lim \inf a_n = \lim \sup a_n = a$, for any $\epsilon$, we can find
a $N$, such that $a - \epsilon < y_n < a < x_n < a + \epsilon, \forall n > N$, and this means
$a - \epsilon < a_n < a + \epsilon, \forall n > N$, i.e. $|a_n - a| < \epsilon$ for all $n > N$.

Another kind of problematic method, because $y_n \le a_n \le x_n$, so
$\lim y_n \le \lim a_n \le \lim x_n$.

**if**: On the other hand, assume $\lim a_n = a$, then for any $\epsilon$, we can find
$N$ s.t. as long as $n > N$, $a_n < a + \epsilon$, that means $x_n \leq a + \epsilon$ for all $n > N$. So it's not possible that $\lim x_n > a$. So we have $\lim x_n \le a$. For the same reason,
$\lim y_n \ge a$. Using (c), we have  $\lim x_n \ge \lim y_n$. So we have
$\lim \inf a_n = \lim \sup a_n = a$.

***Exercise 2.4.8. *** For or each series, find an explicit formula for the sequence of partial sums and determine if the series converges.

(a)

$$
\sum_{n=1}^{\infty} \frac{1}{2^n}
$$
$$
\sum_{n=1}^{m} \frac{1}{2^n} = 1 - \frac{1}{2^m} \rightarrow 1
$$
(b)

$$
\sum_{n=1}^{\infty} \frac{1}{n(n+1)}
$$
$$
\sum_{n=1}^{m} \frac{1}{n(n+1)} = 1 - \frac{1}{m+1} \rightarrow 1
$$
(c)

$$
\sum_{n=1}^{\infty} \log (\frac{n+1}{n})
$$
$$
\sum_{n=1}^{m} \log (\frac{n+1}{n}) = \log (m+1) \rightarrow \infty
$$

***Exercise 2.4.9. *** Complete the proof of Theorem 2.4.6 by showing that if the series $\sum_{n=0}^{\infty} 2^n b_{2^n}$ diverges, then so does $\sum_{n=1}^{\infty} (b_n)$.

Proof: We have $2b_1 > s_1-b1, 2(b1 + b2 + b3) > s_2-b1, 2(b1+\cdots+b_7) > s_3-b1$. If $\sum_{n=0}^{\infty} 2^n b_{2^n}$, $\sum_{n=1}^{\infty} (b_n)$ is also unbounded.

***Exercise 2.4.10 (Infinite Products). *** A close relative of infinite series is the infinite product

$$
\prod_{n=1}^{\infty}
b_n = b_1 b_2\cdots
$$
which is understood in terms of its sequence of partial products

$$
p_m =
\prod_{n=1}^{m} b_n
=
b_1 b_2 \cdots b_m
$$
Consider the special class of infinite products of the form

$$
\prod_{n=1}^{\infty} (1 + a_n) \quad \text{where } a_n \ge 0.
$$
(a) Find an explicit formula for the sequence of partial products in the case where $a_n = 1/n$ and decide whether the sequence converges. Write out the first few terms in the sequence of partial products in the case where $a_n = 1/n^2$ and make a conjecture about the convergence of this sequence.

Solution: 

$$
p_m = 
(1 + 1) * (1 + \frac{1}{2}) * \cdots * (1 + \frac{1}{m})
= 2 \cdot \frac{3}{2} \cdots \frac{m+1}{m} = m+1
$$
So it's not converging.

$$
p_m = (1 + 1) * (1 + \frac{1}{4}) * \cdots * (1 + \frac{1}{m^2}) \\
= 2 * \frac{5}{4} * \frac{10}{9} * \cdots * \frac{m^2+1}{m^2} \\
$$

So $p_1 = 2, p_2 = 2.5, p_3 = 2.78, P_4 = 2.95$


(b) Show, in general, that the sequence of partial products converges if and only if $\sum_{n=1}^{\infty} (a_n)$ converges. (The inequality $1 + x ≤ 3^x$ for positive x will be useful in one direction.)

Proof: Assume $\sum_{n=1}^{\infty} (a_n)$ converges, then $p_m = \prod_{n=1}^{m} (1 + a_m) < 3^{a_1a_2 \dots a_m} < 3^M$, so $p_m$ is bounded.

On the other hand assume $\prod_{n=1}^{\infty} (1 + a_n)$ converges, then
$p_m > a_1 + a_2 + \cdots + a_m$, which can be proved by induction. Then
$a_1 + a_2 + \cdots + a_m$ is bounded and it converges.

## 2.5 Subsequences and the Bolzano–Weierstrass Theorem

***Definition 2.5.1.*** Let $(a_n)$ be a sequence of real numbers, and let $n_1 < n_2 < n_3 < n_4 < n_5 < \dots$ be an increasing sequence of natural numbers. Then the sequence

$$
(a_{n_1}, a_{n_2},a_{n_3},a_{n_4},a_{n_5},\cdots)
$$
is called a subsequence of $(a_n)$ and is denoted by $(a_{n_k})$, where $k ∈ N$ indexes the subsequence.

***Theorem 2.5.2.*** Subsequences of a convergent sequence converge to the same limit as the original sequence.

***Theorem 2.5.5 (Bolzano–Weierstrass Theorem).*** *Every bounded sequence contains a convergent subsequence.*

Sketch of proof: Assume $-M \le a_n \le M$. Divide .$[-M, M]$ into $[-M, 0]$ and $[0, M]$. One of them must contain infinite many $a_n$, call it $I_1$.
Pick one element from $I_1$ and let it be $a_{n_1}$. Then bisect $I_1$, again
one of the segaments must contain an infinite number of $a_n$, let it be
$I_2$, and pick $a_{n_2} \in I_2$ and $n_2 > n_1$. Because

$$
I_1 \supseteq I_2 \supseteq I_3 \supseteq \cdots
$$

According to Nested Interval Property there exists at least one point $x ∈ R$ contained in every $I_k$. Then we can show $(a_{n_k}) \rightarrow x$.

### Exercises

***Exercise 2.5.1.*** Give an example of each of the following, or argue that such a request is impossible.

(a) A sequence that has a subsequence that is bounded but contains no sub- sequence that converges.

(b) A sequence that does not contain 0 or 1 as a term but contains subse- quences converging to each of these values.

(c) A sequence that contains subsequences converging to every point in the infinite set {1, 1/2, 1/3, 1/4, 1/5, . . .}.

(d) A sequence that contains subsequences converging to every point in the infinite set {1, 1/2, 1/3, 1/4, 1/5, . . .}, and no subsequences converging to points outside of this set.

Solution:

(a) False.

(b)

$$
\frac{1}{2},\frac{1}{3},\frac{2}{3},\frac{1}{4},\frac{3}{4},
\frac{1}{5},\frac{4}{5}
$$

(c)

$$
\frac{1}{2},\frac{1}{3},\frac{2}{3},
\frac{1}{4},\frac{2}{4},\frac{3}{4},
\frac{1}{5},\cdots,\frac{4}{5},
\frac{1}{6},\cdots,\frac{5}{6},
\cdots
$$

(d) False. We can always find a subsequence converges to 0.

***Exercise 2.5.2.*** Decide whether the following propositions are true or false, providing a short justification for each conclusion.

(a) If every proper subsequence of $(x_n)$ converges, then $(x_n)$ converges as well.
(b) If $(x_n)$ contains a divergent subsequence, then $(x_n)$ diverges.
(c) If $(x_n)$ is bounded and diverges, then there exist two subsequences of $(x_n)$ that converge to different limits.
(d) If $(x_n)$ is monotone and contains a convergent subsequence, then $(x_n)$ converges.

Solution:

(a) Consider the subsequence $x_2, x_3, x_4, \dots$, it converges, then 
$(x_n)$ converges. So it's true.

(b) True.

(c) True. Based on theorem 2.5.5, we can find a subsequence which converges
to $L$. Since $(x_n)$ diverges, we can find $\epsilon$, such that there are
infinite many $x_n$, which is outside $(L-\epsilon, L+\epsilon)$, then for
those $x_n$, we can again use theorem 2.5.5, to find another sequence which
converges to something other than $L$.

(d) $(x_n)$ is bounded, so it converges. True.

***Exercise 2.5.3.*** (a) Prove that if an infinite series converges, then the associative property holds. Assume a1 + a2 + a3 + a4 + a5 + · · · converges to a limit $L$ (i.e., the sequence of partial sums $(s_n) → L$). Show that any regrouping of the terms

$$
(a_1 + a_2 + \cdots +a_{n_1})+(a_{n_1+1} +···+a_{n_2})+(a_{n_2+1} +···+a_{n_3})+···
$$

leads to a series that also converges to $L$.

Proof: 

We have

$$
s_{n_1} = a_1 + a_2 + \cdots +a_{n_1} \\
s_{n_2} = (a_1 + a_2 + \cdots +a_{n_1})+(a_{n_1+1} +···+a_{n_2})
$$
So any regrouping created a sequence $(s_{n_k})$ is a subsequence of $(s_n)$.
According to theorem 2.5.2, $(s_{n_k})$ converges to $L$.

***Exercise 2.5.4.*** The Bolzano–Weierstrass Theorem is extremely important, and so is the strategy employed in the proof. To gain some more experience with this technique, assume the Nested Interval Property is true and use it to provide a proof of the Axiom of Completeness. To prevent the argument from being circular, assume also that $(1/2^n) → 0$. (Why precisely is this last assumption needed to avoid circularity?)

Proof: 

Axiom of Completeness: Every non empty set of real numbers that is bounded above has a least upper bound.

Assume the non empty set of real numbers is $A$, which is upper bounded by $M$.
Let $S = \{ s | s \le M, s \text{ is a upper bound of} \}$. 

Let $a \in A$ and $I_1 = [a, M] = [c_1, d_1]$. The $I_1$ has two properties:

i. $I_1 \cap S \neq \emptyset$
ii. for any $b < c_1$, $b \notin S$.

Now we can bisect $I_1$, one of the two halves must still satisfy these
2 properties, and we call it $I_2$. We can continue this process to get
$I_1 \supset I_2 \supset I_3 \supset \dots$.

Then According to nested interval property, there exists $s \in I_n, \forall n$.

We will prove $s$ is the least upper bound. First we prove it is an upper bound. Assume $a \in A$, and $a > s$. Since we the
length of $I_n → 0$, we can find $I_n$, such that $a > c, \forall c \in I_n$,
then $I_n$ does not contain any upper bound. And we achieve a contradiction.

Next we prove if $s' < s$, it's not an upper bound. Again, we can find $I_n$,
such that $s' < c_n \le s \le d_n$. According to property ii, $s'$ is not
an upper bound.

So $s$ is the least upper bound.

***Exercise 2.5.5.*** Assume $(a_n)$ is a bounded sequence with the property that every convergent subsequence of $(a_n)$ converges to the same limit $a ∈ R$. Show that $(a_n)$ must converge to a.

Proof: Given $\epsilon$, if there are infinite many $a_n$ that is outside
$(a-\epsilon, a+\epsilon)$, say, in the interval $[a+\epsilon, M]$ then we can find a subsequence $(a_{n_k})$ that converges. Since $a_{n_k} \ge a+\epsilon$,
then $\lim a_{n_k} \ge a+\epsilon$. So we have a contradiction. This idea
is from linearalgebras.com .

***Exercise 2.5.7.*** Extend the result proved in Example 2.5.3 to the case $|b| < 1$; that is, show $\lim (b^n) = 0$ if and only if $−1 < b < 1$.

Proof: 

if part: When $0 < b < 1$, it's example 2.5.3. When $b = 0$, $b^n = 0, \forall n$, so $\lim (b_n) = 0$.

Now consider $-1 < b < 0$. Given any $\epsilon$, because $0 < -b < 1$, so $((-b)^n)$ converges to 0, so we can find $N$,  such that for all $n > N$,  $|(-b)^n - 0| < \epsilon$, and $|(-b)^n|=|-b|^n=|b|^n = |b^n|$. So $|b^n-0| \le \epsilon$, so $b^n \rightarrow 0$.

only if part: when $b = 1$, $b^n = 1$. so $\lim b^n = 1$. When $b>1$, let $b = 1 + \epsilon$, then $b^n = (1+\epsilon)^n \ge 1 + n \epsilon$, so it's not bounded and it does not converge. 

When $b \le -1$, consider the even terms subsequence. Then they either converge
to 1 or not bounded, so they cannot converge to 0.

***Exercise 2.5.8.*** Another way to prove the Bolzano–Weierstrass Theorem is to show that every sequence contains a monotone subsequence. A useful device in this endeavor is the notion of a peak term. Given a sequence $(x_n)$, a particular term $x_m$ is a peak term if no later term in the sequence exceeds it; i.e., if $x_m ≥ x_n$ for all $n≥m$.

(a) Find examples of sequences with zero, one, and two peak terms. Find an example of a sequence with infinitely many peak terms that is not monotone.

Solution: 

zero peak terms: $a_n = 1 - \frac{1}{n}$, which is monotonous increaseing.

one peak term: $1, a_1, a_2, \dots$.

two peak terms: $2, 1, a_1, a_2, \dots$.

infinitely many peak terms: $1, -1, 1/2, -1/2, 1/4, -1/4, \dots$.

(b) Show that every sequence contains a monotone subsequence and explain how this furnishes a new proof of the Bolzano–Weierstrass Theorem.

Proof: Assume there are infinitely many peak terms in $(a_n)$, let the first
be $a_{n_1}$, second be $a_{n_2}$ and so on, then $(a_{n_k})$ is a monotonous
decreasing sequence.

Assume there are only finite many peak terms in $(a_n)$, and assume when $n > N$, $a_n$ are not peak terms. Find a non peak term $a_{n_1}$ and $n_1 > N$,
since it's not we can find a non peak term $a_{n_2} > a_{n_1}$, since $a_{n_2}$
is also non peak term, we can find $a_{n_3} > a_{n_2}$ and $n_3 > n_2$.
And so on. Then $(a_{n_k})$ is a monotonous increasing sequence.

If $(a_n)$ is bounded, so is $(a_{n_k})$. Then $(a_{n_k})$ converges.

***Exercise 2.5.9.*** Let $(a_{n})$ be a bounded sequence, and define the set

$$
S=\{x∈R:x<a_n \text{ for infinitely many terms } a_n\}.
$$
Show that there exists a subsequence $(a_{n_k} )$ converging to $s = \sup S$.
(This is a direct proof of the Bolzano–Weierstrass Theorem using the Axiom of Completeness.)

Proof: Consider $s-1$, then there exists $x_1 \in S$, such that $s \ge x_1 > s-1$, then there are infinitely many terms $a_n > x_1$. If there are infinitely many terms $a_n > s+1$, then $s+1 \in S$, so $s$ cannot be a superum of $S$. so at least there
is $a_{n_1} \in [s-1, s+1]$.

For the same reason we can find $a_{n_2} \in [s-1/2, s+1/2]$ and $n_2 > n_1$.
For any $k$, we can find $a_{n_k} \in [s-\frac{1}{k}, s+\frac{1}{k}]$, and

$$
n_k > n_{k-1} > \cdots > n_2 > n_1
$$

Then for any given $\epsilon$, we can find $k$ such $\frac{1}{k} < \epsilon$,
then for any $m > k$, $a_{n_m} \in [s-\frac{1}{k}, s+\frac{1}{k}]$.
Then $(a_{n_k}) \rightarrow x$.

## 2.6 The Cauchy Criterion

### Exercises

***Exercise 2.6.1.*** Every convergent sequence is a Cauchy sequence.

Proof: Assume $a_n \rightarrow a$, we can find $N$, such that $m, n > N$,
then $|a_n - a| < \epsilon$, $|a_m - a| < \epsilon$.

So

$$
|a_m - a_n| = |a_m - a + a - a_n| \le |a_n - a| + |a_m - a| \le 2 \epsilon
$$

***Exercise 2.6.2.*** Give an example of each of the following, or argue that such a request is impossible.
(a) A Cauchy sequence that is not monotone.
(b) A Cauchy sequence with an unbounded subsequence.
(c) A divergent monotone sequence with a Cauchy subsequence.
(d) An unbounded sequence containing a subsequence that is Cauchy.

(a)

$$
a_n = (-1)^n \frac{1}{n}
$$

(b) impossible. Cauchy sequence converges, so every subsequence converges.

(c) impossible. If it has a Cauchy subsequence, then this subsequence converges. So the original sequence is bounded.

(d)

$$
0, 1, 1, 1, 2, 1, 3, 1, 4, 1, \dots
$$

***Exercise 2.6.3.*** 

(a) Give a direct argument that $(x_n + y_n)$ is a Cauchy sequence that does not use the Cauchy Criterion or the Algebraic Limit Theorem.

(b) Do the same for the product $(x_ny_n)$.

Solution:

(a) Easy.

(b)

$$
|x_ny_n - x_my_m| = |x_ny_n - x_ny_m + x_ny_m - x_my_m| \\
\le |x_ny_n - x_ny_m| + |x_ny_m - x_my_m|
= |y_n - y_m||x_n| + |x_n - x_m||y_m| \\
\le \epsilon M + \epsilon M
$$

***Exercise 2.6.4.*** Let $(a_n)$ and $(b_n)$ be Cauchy sequences. Decide whether each of the following sequences is a Cauchy sequence, justifying each conclusion.

(a) $c_n = |a_n − b_n|$
(b) $c_n = (−1)^na_n$
(c) $c_n = [[an]]$, where $[[x]]$ refers to the greatest integer less than or equal to $x$.

Solution:

(a) It's a Cauchy sequence.

$$
|c_m - c_n| = |(a_m-b_m) - (a_n-b_n)| \le |(a_m-b_m)| + |(a_n-b_n)| \\
< \epsilon + \epsilon = 2 \epsilon
$$
(b) No. Consider

$$
a_n = 1 - \frac{1}{n}
$$

(c) No. Consider

$$
a_n = (-1)^n \frac{1}{n}
$$

then

$$
(x_n) = -1,0,-1,0,\dots
$$

***Exercise 2.6.5.*** Consider the following (invented) definition: A sequence $(s_n)$ is pseudo-Cauchy if, for all $ε > 0$, there exists an $N$ such that if $n ≥ N$, then $|s_{n+1} − s_n| < ε$.

Decide which one of the following two propositions is actually true. Supply a proof for the valid statement and a counterexample for the other.

(i) Pseudo-Cauchy sequences are bounded.
(ii) If $(x_n)$ and $(y_n)$ are pseudo-Cauchy, then $(x_n + y_n)$ is pseudo-Cauchy as well.

Solution:

(i) Consider the harmonic seris, which satisfy $|s_{n+1} − s_n| < ε$,
and it's not bounded.

(ii)

$$
|x_{n+1}+y_{n+1} - (x_n+y_n)| \le
|x_{n+1}-x_n| + |y_{n+1} - y_n| < ε
$$

***Exercise 2.6.6.*** Let’s call a sequence $(a_n)$ *quasi-increasing* if for all $ε > 0$ there exists an $N$ such that whenever $n > m ≥ N$ it follows that $a_n > a_m − ε$.

(a) Give an example of a sequence that is quasi-increasing but not monotone or eventually monotone.

(b) Give an example of a quasi-increasing sequence that is divergent and not
monotone or eventually monotone.

(c) Is there an analogue of the Monotone Convergence Theorem for quasi- increasing sequences? Give an example of a bounded, quasi-increasing sequence that doesn’t converge, or prove that no such sequence exists.

Solution:

(a) See (b)

(b) Consider the following sequence

$$
a_1 = \frac{1}{2} + 1  \\
a_2 = \frac{1}{2} \\
a_3 = \frac{1}{2} + 1 + \frac{1}{4} + \frac{1}{3} \\
a_4 = \frac{1}{2} + 1 + \frac{1}{4} \\
a_{2n+1} = a_{2n} + \frac{1}{2n+2} + \frac{1}{2n+1} \\
a_{2n+2} = a_{2n} + \frac{1}{2n+2} \\
$$

This sequence is not monotone or eventually monotone. It's also diverge.

Also, if $m$ is odd, then
$$
|a_m - a_{m+1}| = \frac{1}{m}   \\
|a_m - a_{m+3}| = \frac{1}{m+3} \\
$$

If $m$ is even, then

$$
|a_m - a_{m+2}| = \frac{1}{m+2}
$$

(c) Assume $(a_n)$ is bounded and quasi-increasing. From BW, let $a$ be the limit of subsequence $(a_{n_k})$.

Assume $|a_{n_k} - a| < \epsilon/2$, then

$$
|a_m - a| = |(a_m - a_{n_k}) + (a_{n_k} - a)| \le 
|(a_m - a_{n_k})| + |(a_{n_k} - a)| < \epsilon
$$

***Exercise 2.6.7.*** Exercises 2.4.4 and 2.5.4 establish the equivalence of the Axiom of Completeness and the Monotone Convergence Theorem. They also show the Nested Interval Property is equivalent to these other two in the presence of the Archimedean Property.

(a) Assume the Bolzano–Weierstrass Theorem is true and use it to construct a proof of the Monotone Convergence Theorem without making any appeal to the Archimedean Property. This shows that BW, AoC, and MCT are all equivalent.

Proof: Assume $(a_n)$ is monotone increasing and bounded. And because BW is true, we can find a subsequence $(a_{n_k})$ converge to $a$. Given $\epsilon$,
we can find $N$ such that $n_k > N$, $|a_{n_k} - a| < \epsilon$.


Because $(a_{n_k})$ is also monotone increasing, so $a_{n_k} \le a$.
Note here, this does not need to use AoC. If $a_{n_k} > a$, then $\forall n_i >= n_k, a_{n_i} > a$, so $\lim a_{n_k} \ne a$.


Now consider $n_{k+1} \ge n \ge n_k$.
Also note here, this does not need to use Archimedean property.
then $a_{n_k} \le a_n \le a_{n_{k+1}} \le a$, so we have $|a_{n} - a| < \epsilon$.

(b) Use the Cauchy Criterion to prove the Bolzano–Weierstrass Theorem, and find the point in the argument where the Archimedean Property is implicitly required. This establishes the final link in the equivalence of the five characterizations of completeness discussed at the end of Section 2.6.

Proof: We just use the same way to prove Bolzano–Weierstrass Theorem.
Because all $a_{n_k}$ falls into the same interval. Then
$$
|a_{n_k}-a_{n_l}| < \frac{L}{2^n} < \epsilon
$$
So the subsequence $(a_{n_k})$ is a Cauchy Sequence.

The Archimedean Property is implicitly required here:

$$
\frac{L}{2^n} < \epsilon
$$

(c) How do we know it is impossible to prove the Axiom of Completeness starting from the Archimedean Property?

Solution: If it is possible, then $\mathbb{Q}$ is complete. This is not true.
We have a contradiction.

## 2.7 Properties of Infinite Series

***Theorem 2.7.2 (Cauchy Criterion for Series).*** The series $\sum_{k=1}^{\infty} a_k$ converges if and only if, given $ε > 0$, there exists an $N ∈ N$ such that whenever $n>m≥N$ it follows that
$|a_{m+1} +a_{m+2} +···+a_n|<ε$.

***Theorem 2.7.3.*** If the series $\sum_{k=1}^{\infty}a_k$ converges, then $(a_k) → 0$.

***Theorem 2.7.4 (Comparison Test).*** Assume $(a_k)$ and $(b_k)$ are sequences satisfying $0 ≤ a_k ≤ b_k$ for all $k∈N$.

(i) if $\sum_{k=1}^{\infty} b_k$ converges, then $\sum_{k=1}^{\infty} a_k$ converges.

(ii) if $\sum_{k=1}^{\infty} a_k$ diverges, then $\sum_{k=1}^{\infty} b_k$ diverges.

Proof:

$$
|a_{m+1} +a_{m+2} +···+a_n|≤|b_{m+1} +b_{m+2} +···+b_n|
$$

***Theorem 2.7.6 (Absolute Convergence Test).*** If the series $\sum_{k=1}^{\infty} |a_k|$ converges, then $\sum_{k=1}^{\infty} a_k$ converges as well.

***Theorem 2.7.7 (Alternating Series Test).*** Let $(a_n)$ be a sequence satisfying,

(i) $a_1 \ge a_2 \ge a_3 \ge \dots \ge a_n \ge a_{n+1} \ge \dots$
(ii) $(a_n) \rightarrow 0$

Then, the alternating series $\sum_{n=1}^{\infty}(-1)^{n+1}a_n$ converges.

***Definition 2.7.8.*** If $\sum_{k=1}^{\infty} |a_k|$ converges, then we say that the original series $\sum_{k=1}^{\infty} a_k$ converges absolutely.
If, on the other hand, the series
$\sum_{k=1}^{\infty} a_k$ converges but the series of absolute values
$\sum_{k=1}^{\infty} |a_k|$ does not converge, then we
say that the original series $\sum_{k=1}^{\infty} a_k$ converges conditionally.


***Definition 2.7.9.*** Let $\sum_{k=1}^{\infty} a_k$ be a series. A series
$\sum_{k=1}^{\infty} b_k$ is called a rearrangement of
$\sum_{k=1}^{\infty} a_k$ if there exists a one-to-one, onto function
$f:N \rightarrow N$ such that $b_{f(k)} = a_k$ for all $k \in \mathbb{N}$.

***Theorem 2.7.10.*** If a series converges absolutely, then any rearrangement of this series converges to the same limit.

Proof:

Let

$$
s_n = \sum_{k=1}^{n} a_k \\
t_m = \sum_{k=1}^{m} b_k
$$
Assume $s_n \rightarrow A$.

We can find $N_1$, such that $|s_n - A| < \frac{ε}{2}$ for all $n \ge N_1$.

We can also find $N_2$, such that for all $n > m+1 \ge N_2$

$$
\sum_{k=m+1}^{n} |a_k| < \frac{ε}{2}
$$

Let $N = \max \{N_1, N_2\}$ and let

$$
M = \max \{f(k): 1 \le k \le N\}
$$

Then for $m \ge M$ consider $t_m - s_N $. It only consists of a finite set of terms, the absolute values of which appear in the tail $\sum_{k=m+1}^{n} |a_k|$.

### Exercises

***Exercise 2.7.1.*** Proving the Alternating Series Test (Theorem 2.7.7) amounts to showing that the sequence of partial sums converges.

$$
s_n = a_1 − a_2 + a_3 − · · · ± a_n
$$
(a) Prove the Alternating Series Test by showing that $(s_n)$ is a Cauchy
sequence.

Proof: Consider $m > n > N$, if $n, m$ are both odd or even.

$$
|a_m - a_n | = |a_{n+1} - a_{n+2} + \dots + a_{m-1} - a_m| \\
= a_{n+1} - a_{n+2} + \dots + a_{m-1} - a_m \\
$$
Note that

$$
|a_m - a_n | = a_{n+1} - a_{n+2} + \dots + a_{m-1} - a_m
\le a_{n+1}
$$

Since $(a_n) \rightarrow 0$, then $| a_m - a_n | \rightarrow 0$.

Now consider $m > n > N$, if one of $n, m$ is odd, and the other is even.

$$
| a_m - a_n | = |a_{n+1} - a_{n+2} + \dots - a_{m-1} + a_m| \\
$$
Since $a_{n+1} - a_{n+2} + \dots - a_{m-1} + a_m > 0$, then

$$
| a_m - a_n | = a_{n+1} - a_{n+2} + \dots - a_{m-1} + a_m \\
= a_{n+1} - (a_{n+2} - a_{n+3}) - \cdots - (a_{m-1} - a_m) \\
\le a_{n+1}
$$
Then $| a_m - a_n | \rightarrow 0$

(b) Supply another proof for this result using the Nested Interval Property
(Theorem 1.4.1).

Proof: consider intervals

$$
I_1 = [s_2, s_1], \\
I_2 = [s_4, s_3], \dots \\
I_n = [s_{2n}, s_{2n-1}] \\
$$
The length of $I_n$ = $a_{2n} \rightarrow 0$. Let $s$ belongs all these
intervals, then $(s_n) \rightarrow s$.

(c) Consider the subsequences $(s_{2n})$ and $(s_{2n+1})$, and show how the Monotone Convergence Theorem leads to a third proof for the Alternating Series Test.

Proof: 

$$
s_{2n+2} - s_{2n} = a_{2n+1} - a_{2n+2} \ge 0
$$

and

$$
s_{2n+3} - s_{2n+1} = a_{2n+3} - a_{2n+2} \le 0
$$

And also

$$
s_{2n+1} \ge s_{2n} \ge s_2 \\
s_{2n} \le s_{2n-1} \le s_1
$$

So both $(s_{2n})$ and $(s_{2n+1})$ converges. Also

$$
\lim s_{2n+1} - s_{2n} = \lim a_{2n+1} = 0
$$

So they converge to the same limit $s$. And it can show the original sequence
also converges.

***Exercise 2.7.4.*** Give an example of each or explain why the request is impossible referencing the proper theorem(s).

(a) Two series $\sum x_n$ and $\sum y_n$ that both diverge but where
$\sum x_ny_n$ converges.

Solution: Consider $x_n = y_n = \frac{1}{n}$

(b) A convergent series $\sum x_n$ and a bounded sequence $(y_n)$ such that $\sum x_ny_n$ diverges.

Solution: Consider 

$$
x_n = (-1)^n\frac{1}{n}, y_n = (-1)^n
$$

Then $\sum x_ny_n$ is the harmonic series and diverges.

(c) Two sequences $(x_n)$ and $(y_n)$ where $\sum x_n$ and $\sum x_n + y_n$ both converge but $(y_n)$ diverges.

Solution: impossible, due to algebraic limit theorem for series.

(d) A sequence $(x_n)$ satisfying $0 ≤ x_n ≤ 1/n$ where $\sum(−1)^nx_n$ diverges.

Solution: Consider

$$
1, 0, \frac{1}{3}, 0, \frac{1}{5}, \dots
$$

***Exercise 2.7.5.*** Now that we have proved the basic facts about geometric series, supply a proof for Corollary 2.4.7, i.e. The series $\sum_{n=1}^{\infty} \frac{1}{n^p}$ converges if and only if $p > 1$.

***Exercise 2.7.6.*** Let’s say that a series *subverges* if the sequence of partial sums contains a subsequence that converges. Consider this (invented) definition for a moment, and then decide which of the following statements are valid propositions about subvergent series:

***Exercise 2.7.8.*** Consider each of the following propositions. Provide short proofs for those that are true and counterexamples for any that are not.

(a) If $\sum a_n$ converges absolutely, then $\sum a_n^2$ also converges absolutely.

(b) If $\sum a_n$ converges and $(b_n)$ converges, then $\sum a_nb_n$ converges.

(c) If $\sum a_n$ converges conditionally, then $\sum n^2 a_n$ diverges.

Solution:

(a) True.

(b) False. Consider the following alternating sequence

$$
1, -\frac{1}{\sqrt{2}}, \frac{1}{\sqrt{3}}, -\frac{1}{\sqrt{4}}
$$
According to Theorem 2.7.7 (Alternating Series Test), $\sum a_n$ converges.

Now consider $(b_n) = (a_n)$, Then $(a_nb_n)$ is

$$
1, \frac{1}{2}, \frac{1}{3}, \dots
$$

And $\sum a_nb_n$ doesn't converge.

(c) need more time to work on.

***Exercise 2.7.9 (Ratio Test).*** Given a series $\sum_{n=1}^{\infty} a_n$ with $a_n \ne 0$, the Ratio Test states that if $(a_n)$ satisfies

$$
\lim |\frac{a_{n+1}}{a_n}| = r < 1
$$

then the series converges absolutely.

(a) let $r < r' < 1$, why there exists an $N$ such that $n≥N$ implies $|a_{n+1}| ≤ |a_n|r′$.

Proof: Assume $r' \ge r + \epsilon$, then there exists an $N$ such that $n≥N$
and $|\frac{a_{n+1}}{a_n}| < r + \epsilon \le r'$, so $|a_{n+1}| ≤ |a_n|r′$.

(b) Why does $|a_N|\sum (r′)^n$ converge?

Proof: because it's geometric series and $0 < r' < 1$.

(c) Now, show that $\sum |a_n|$ converges, and conclude that $\sum a_n$ converges.

Proof: Because $0 < |a_n| \le |a_N| (r')^n$, and according to Comparison Test,
$\sum |a_n|$ converges. So does $\sum a_n$.

***Exercise 2.7.10 (Infinite Products).*** Review Exercise 2.4.10 about infinite products and then answer the following questions

(a) Does $\frac{2}{1} \cdot \frac{3}{2} \cdot \frac{5}{4} \cdot $ converge?

Proof: It is. Because it's

$$
\prod_{n=0}^{\infty} (1+\frac{1}{2^n}) < 3^{\sum(\frac{1}{2})^n} = 9
$$

(b) The infinite product $\frac{1}{2} \cdot \frac{3}{4} \cdot \frac{5}{6} \cdot $ certainly converges. Why? Does it converge to zero?

Proof: Because it is monotonous decreasing. Need more time to think about the limit.

$$
(1- \frac{1}{2n})^n\\
$$

(c) Show the following sequence converges.

$$
(\frac{2\cdot2}{1\cdot3}) \cdot
(\frac{4\cdot4}{3\cdot5}) \cdot
(\frac{6\cdot6}{5\cdot7}) \cdot
(\frac{8\cdot8}{7\cdot9}) \cdot
$$

Proof:

$$
\prod_{n=1}^{\infty} (1 + \frac{1}{(2n+1)(2n+3)}) \\
\le 3^{\frac{1}{2}\sum \frac{2}{3} \frac{2}{15} \frac{2}{35}} \\
\le 3 ^ \frac{1}{2}
$$


**Exercise 2.7.11.*** Find examples of two series $\sum a_{n}, \sum b_{n}$ both of which diverge but for which $\sum \min \{a_{n}, b_n\}$ converges. To make it more challenging, produce examples where $(a_{n}) , (b_{n})$ are strictly positive and decreasing.

Solution:

(a) Consider the following 2 sequences.

$$
1, \frac{1}{2^2}, \frac{1}{3}, \frac{1}{4^2}, \\
1, \frac{1}{2}, \frac{1}{3^2}, \frac{1}{4}, \\
$$
(b) I need more time to think about the 2nd half.

***Exercise 2.7.12 (Summation-by-parts).*** Let $(x_n)$ and $(y_n)$ be sequences, let $s_n = \sum_{k=1}^{n} x_k $ and set $s_0 = 0$. Use the observation that $x_j = s_j −s_{j−1}$ to verify the formula

$$
\sum_{j=m}^n x_j y_j = \\
\sum_{j=m}^n (s_j −s_{j−1})y_j = \\
\sum_{j=m}^n s_j y_j - s_jy_{j+1} + s_jy_{j+1} - s_{j−1}y_j
$$
Now, let's consider

$$
\sum_{j=m}^n s_jy_{j+1} - s_{j−1}y_j =\\
(x_1 + \dots + x_m)y_{m+1} - (x_1 + \dots + x_{m-1})y_m + \\
(x_1 + \dots + x_{m+1}) y_{m+2} - (x_1 + \dots + x_{m}) y_{m+1} + \\
(x_1 + \dots + x_{m+2}) y_{m+3} - (x_1 + \dots + x_{m+1}) y_{m+2} + \\
+ \dots \\
(x_1 + \dots + x_{n}) y_{n+1} - (x_1 + \dots + x_{n-1}) y_{n} \\
= s_ny_{n+1} - s_{m-1}y_m
$$

***Exercise 2.7.13 (Abel’s Test).*** Abel’s Test for convergence states that if the $\sum_{k=1}^n x_k$ converges and if $(y_k)$ is a sequence satisfying

$$
y_1 \ge y_2 \ge y_3 \ge \cdots \ge 0,
$$


Proof:

$$
\sum_{k=1}^n |s_k (y_k - y_{k+1})| = \\
\sum_{k=1}^n |s_k ||(y_k - y_{k+1})| \\
= \sum_{k=1}^n |s_k | (y_k - y_{k+1}) \\
\le \sum_{k=1}^n M (y_k - y_{k+1}) \le y_1M
$$

# Chapter 3 Basic Topology of R

## 3.1 Discussion: The Cantor Set

* Let

$$
C_0 = [0,1], \\
C_1 = [0, \frac{1}{3}] \cup [\frac{2}{3}, 1], \\
C_2 = [0, \frac{1}{9}] \cup [\frac{2}{9}, \frac{1}{3}]
      \cup [\frac{2}{3}, \frac{7}{9}]
      \cup [\frac{8}{9}, 1]
$$

* Then we define the Cantor set $C$ be 

$$
C = \cap_{n=0}^\infty C_n
$$

* First, we notice $C$ is not empty, because $0 \in C$ and $1 \in C$.
* Second, we notice if $y$ is an endpoint in $C_n$, then $y \in C_n, \forall n$. Because endpoints are never removed.
* Third, If we calculate the length that are removed from $[0,1]$, it's

$$
\frac{1}{3} + 2\left( \frac{1}{9} \right) + 4 \left( \frac{1}{27} \right) \cdots = \frac{\frac{1}{3}}{1 - \frac{2}{3}} = 1
$$
So the length of $C$ is 0!

* Fourth, we can establish a 1-1 correspondence between $C$ and $\{0,1\}$
sequence. So $C$ must be uncountable. The cardinality of $C$ is as large as
$\mathbb{R}$.
* Finally, what about $C$'s dimension? $2 = 3^x$, so $x = \log 2 / \log 3$.

## 3.2 Open and Closed Sets

* Given $a \in \mathbb{R}$ and $\epsilon > 0$, $\epsilon$-neighborhood of $a$
is the set

$$
V_{\epsilon}(a) = \{
x \in \mathbb{R} : |x-a| < \epsilon
\}
$$

***Definition 3.2.1.*** A set $O \subseteq \mathbb{R}$ is open if for all
points $a \in O$ there exists $\epsilon$-neighborhood $V_{\epsilon}(a) \subseteq O$.

***Example 3.2.2.***

(i). $\mathbb{R}$ is an open set.
(ii). $(c,d) = \{x \in \mathbb{R} : c < x < d \}$

***Theorem 3.2.3.***

(i) The union of an arbitrary collection of open sets is open.
(ii) The intersection of a finite collection of open sets is open.

***Definition 3.2.4.*** A point $x$ is a *limit point* of a set $A$ if every ε-neighborhood $V_{\epsilon}(a)$ of $x$ intersects the set $A$ at some point other than $x$.

***Theorem 3.2.5.*** A point $x$ is a limit point of a set $A$ if and only if
$x = \lim a_n$ for some sequence $(a_n)$ contained in $A$ satisfying
$a_n \ne x$ for all $n \in \mathbb{N}$.

***Definition 3.2.6.*** A point $a ∈ A$ is an isolated point of $A$ if it is not a limit point of $A$.

***Definition 3.2.7.*** A set $F ⊆ R$ is closed if it contains its limit points.

***Theorem 3.2.8.*** A set $F ⊆ R$ is closed if and only if every Cauchy sequence contained in $F$ has a limit that is also an element of $F$.

* Proof: See exercise 3.2.5.

***Example 3.2.9.*** 

(i) Consider

$$
A = \Biggl\{ \frac{1}{n} : n \in \mathbb{N} \Biggr\}
$$
Then each point of $A$ is isolated. $0$ is only limit point of $A$.
Because $0 \notin A$, $A$ is not closed. The set $F = A \cup \{0\}$ is closed
and is called closure of $A$.

(ii) Let’s prove that a closed interval

$$
[c,d] = \{ x \in \mathbb{R} : c \le x \le d\}
$$
is a closed set. Assume $x$ is a limit point of $[c,d]$, then according Theorem 3.2.5 there exists $(x_{n}) \subseteq [c,d]$ with $(x_{n}) \rightarrow x$, we need to prove $x \in [c,d]$. We can use Order Limit Theorem, because
$c \le x_n \le d$, then $c \le x \le d$.

(iii) Consider the set $Q \subseteq R$ of rational numbers. Its set
of limited points is $R$.

Consider $y \in R$, and consider any neighborhood $V_{\epsilon}(y) = (y - ε, y + ε)$, Theorem 1.4.3 allows us to conclude that there exists a rational number $r \ne y$ that falls in this neighborhood. Thus, $y$ is a limit point of $Q$.

***Theorem 3.2.10 (Density of Q in R).*** For every $y ∈ R$, there exists a
sequence of rational numbers that converges to $y$.

Proof. Combine the preceding discussion with Theorem 3.2.5.

### Closure

***Definition 3.2.11.*** Given a set $A ⊆ R$, let $L$ be the set of all limit points of $A$. The closure of $A$ is defined to be $\bar{A} = A ∪ L$.

***Theorem 3.2.12.*** For any $A ⊆ R$, the closure $\bar{A}$ is a closed set and is the smallest closed set containing $A$.

Proof. If $\bar{a}$ is a limit point of $\bar{A}$, then consider $V_{\epsilon}(\bar{a})$, there exist $a \in \bar{A}$, such that $a \in V_{\epsilon}(\bar{a})$. Becuase $V_{\epsilon}(\bar{a})$ is open, we can find
$V_{\epsilon'}(a) \subset V_{\epsilon}(\bar{a})$. Since $a$ is either in $A$
or is a limit point of $A$, we can find $a'' \in A$ and $a'' \in V_{\epsilon'}(a)$, and thus $a'' \in V_{\epsilon}(\bar{a})$.

So $\bar{a}$ is also a limit point of $A$, so $\bar{a} \in \bar{A}$.

For the 2nd part, $A'' \supseteq A$ is a closed set. Then $A'' \supseteq L$,
so $A'' \supseteq \bar{A}$.

### Complements

***Theorem 3.2.13.*** A set $O$ is open if and only if $O^c$ is closed. Likewise, a set $F$ is closed if and only if $F^c$ is open.

# Chapter -1 Commonly used symbols

$$
\mathbb{R}, \\
ε \\
V_{\epsilon}(a) = (a - ε, a + ε)\\
\cap_{n=1}^{\infty} \\
(a_{n}) , (b_{n}) n\in \mathbb{N} \\
\sum a_{n}, \sum b_{n} \\
\sum_{n=1}^{\infty} \\
\prod_{n=1}^{\infty} \\
\frac{1}{n}, \frac{1}{n^2} \\
\forall n > N \\
±, ≥, ∈, ⊆ \\
\bar{A} \\
$$

## Solution manuals

* [linearalgebras.com](https://linearalgebras.com/solution-understanding-analysis.html)
* [github](https://github.com/mikinty/Understanding-Analysis-Abbott-Solutions)
* [github UlisseMini](https://github.com/UlisseMini/understanding-analysis-solutions)

