---
title: "Notes-on-Abstract-Algebra-Dummit-Exercises"
author: "Yang Ge"
date: "9/28/2017"
output:
  html_document:
    keep_md: false
    toc: true
---

# Chapter 1
## section 1.1

### ex01

* a. No
* b. Yes

$$
(ab)c = (a+b+ab)c = (a+b+ab+c+ac+bc+abc) \\
a(bc) = a(b+c+bc) = (a+b+c+bc+ab+ac+abc)
$$

* c. No
* d. Yes

$$
((a, b)(c,d))(e,f) = (ad+bc,bd)(e,f) = (adf+bcf+bde,bdf)\\
(a, b)((c,d)(e,f)) = (a,b)(cf+de, df) = (adf+bcf+bde, bdf)
$$

* e. No

### ex03

According definition
$$
\bar{a} + (\bar{b} + \bar{c}) = \bar{a} + \overline{b+c} = \overline{a+b+c} \\
(\bar{a} + \bar{b}) + \bar{c} = \overline{a+b} + \overline{c} = \overline{a+b+c}
$$

### ex04

Same as ex03

### ex05

Condier $\bar{0}$, it does not have inverse.
First it is not identity, because $\bar{1}$ is.
Then the product of it with other elements is itself, not $\bar{1}$.

### ex06

* (a) yes. Assume this set is $G$, then

$$
\frac{p_1}{q_1} + \frac{p_2}{q_2} = \frac{p_1q_2+p_2q_1}{q_1q_2} \in G
$$

The associativity can be satisfied. Inverse and identity are all in $G$.

* (b) no. Assume this set is $G$. $1/6 \in G$, but $1/6+1/6=1/3 \notin G$.

* (c) no. $1/2 \in G$, but $1/2+1/2=1 \notin G$.

* (d) no. $2.1 \in G, -1.2 \in G$, but $2.1 - 1.2 = 0.9 \notin G$.

* (e) yes.

* (f) no. $1/2+1/3=5/6 \notin G$

### ex07

* We try to prove the following

$$
(a \star b) \star c = a+b+c - [a+b+c]
$$

We distiguish 2 cases:

* case 1: $a+b<1$. In this case we have:

$$
(a \star b) \star c = (a+b) \star c = a+b+c - [a+b+c]
$$

* case 2: $a+b \ge 1$. In this case we have:

$$
(a \star b) \star c = (a+b-1) \star c = (a+b-1)+c - [(a+b-1)+c] \\
= a+b+c - 1 - ([a+b+c]-1) = a+b+c - [a+b+c]
$$

For the same reason, we also have

$$
a \star (b \star c) = a+b+c - [a+b+c]
$$

Then it's associative. It's easy to see it's commutative.
For $a \in G, (1-a)\star a = (1-a+a) -[1-a+a]=1-1=0$ So all have inverse.

### ex08

(a) is trival
(b) $1 \in G, i \in G$. But $(1+i) \notin G$, because $1+i=\sqrt{2} e^{\pi/4}$. So the norm
of $1+i$ must be greater than 1.

### ex20

According to ex19.
if $|x|=k$, then $x^k=1$, then $(x^{-1})^k=(x^k)^{-1}=1^{-1}=1$.
And if $m <= k$, such that $(x^{-1})^m = 1$, then $(x^m)^{-1}=1$, then $x^m=1$, $m = k$.

### ex21

Assume $n = 2k+1$, according to ex20, then $x = x \cdot e = x \cdot x^{2k+1} = x ^ {2(k+1)}$.

### ex22

(a) Assume $|x| = n$, then $(gxg^{-1})^n = gx^ng^{-1} = gg^{-1} = 1$.
But if $k<=n$ and $(gxg^{-1})^k=1$, then $gx^kg^{-1} = 1$, then $x^k=1$, we have $k=n$.
So $|gxg^{-1}| = n$.
(b) Let $ba = b (ab) b^{-1}$, so $|ab|=|ba|$.

### ex23

First $1 = x^n = x^{st}= (x^s)^t$
then if $(x^s)^{t'}= x^{st'} = 1$, we must have $st' \ge n = st$, so $t' \ge t$.
Then $|x^s|=t$

### ex24

(a) For $n \ge 0$
Assume $(ab)^n=a^n b^n$, then $(ab)^{n+1}=(ab)^n (ab) = (a^n b^n) (ab) = (a^n a)(b^n b) = a^{n+1}b^{n+1}$
(b) For $n = -k \le 0$, then $(ab)^n = (ab)^{-k} = ((ab)^{-1})^k = ((ba)^{-1})^k = (a^{-1}b^{-1})^k$. Because $b^{-1}a^{-1}=(ab)^{-1}=(ba)^{-1}=a^{-1}b^{-1}$, $a^{-1}$ and $b^{-1}$
are communting elements. $(a^{-1}b^{-1})^k = a^{-k}b^{-k} = a^nb^n$.

### ex25

(a) Since $a^2 = 1$, we have $a^{-1} = a$ for all $a \in G$.
(b) $ab = (ab)^{-1} = b^{-1}a^{-1} = ba$.

### ex27

(a) Let $H = \{x^n | x \in Z\}$.
(b) Closure: $a, b \in H$, then $a = x^i, b = x ^ j, ab = x^ix^j = x^{i+j} \in H$.
(c) Indentity: $e = x^0 \in H$.
(d) Inverse: $a = x^n \in H$, then $a^{-1} = (x^{n})^{-1} = x^{-n} \in H$.

### ex29

(a) if A and B are abelian, $(a_1, b_1)(a_2, b_2) = (a_1a_2, b_1b_2) = (a_2a_1, b_2b_1)= (a_2, b_2)(a_1, b_1)$
(b) if $A \times B$ is abelian, $(a_2a_1, 1 \cdot 1)=(a_2, 1)(a_1, 1)=(a_1, 1)(a_2, 1) = (a_1a_2, 1)$. So we have $a_1a_2 = a_2a_1$. So $A$ is abelian. Same argument holds for $B$.

### ex30

(a) $(a, 1)(1, b) = (a\cdot1, 1\cdot b) = (1 \cdot a, b \cdot 1)=(1,b)(a,1)$
(b) Assume $|a|=p, |b|=q, |(a,b)|=r, \text{lcm}(p,q) = s$. Then $a^r = 1 \implies p|r$. For the same reason $q|r$.
    So $s | r$. On the other hand $a^s=1, b^s=1$, then $(a,b)^s=1$. So $r|s$. Together we have
    $r = s$.

### ex31

If $g \in t(G)$, then $g \neq g^{-1} \in t(G)$, we pair $g, g^{-1}$ together. $t(G)$
has even number of elements. Because $e \notin t(G)$ and $G$ has even order, there must
be another element $g$ not belong to $G$, and $g^2=1$.

### ex32

(a) if $x = x^k$ and $k <= n-1$, then $x^{-1} \cdot x = x^{-1} \cdot x^{k} = x^{k-1}=1$.
Then $k-1 < n$, $|x| < n$. We have a contradiction.

### ex33

(a) if $x^i = x^{-i}$, then $x^{2i} = x^{i} \cdot x^{-i} = 1$.
since $|x| = n$,  $2i > n$. Then $x^{2i-n} = 1$, we must have $2i-n \ge n$.
Then $i \ge n > n-1$.
(b) $x^i = x^{-i}$, then $x^i \cdot x^i = x^{-i} \cdot x^i = e$, we must have $i = k$.

### ex34

Assume $x^n = x^m, m > n$, then $x^{-n} \cdot x^{m} = x^{m-n} = e$. Then $x$ is not infinite
order. We have a contradiction.

### ex36 Cannot figure out

## section 1.2 Dihedral group

* **_2.1.0 Some Properties about $D_{2n}$_:**

(1) $1,r,r^2,\dots,r^{n-1}$ are all distinct and $|r|=n$

To see they are different, just need to see vertex 1's position is all different
  for any $r^{i}$. And rotation $n \cdot 2\pi/n$ makes all vertices go back to original
  position.

(2) $|s|=2$

Assume ${1,2,3}$, with $s$, it becomes ${1,3,2}$, and 2nd time, makes it ${1,2,3}$.
If it's ${1,2,3,4}$, with $s$, it's ${1,4,3,2}$, and 2nd time, makes it ${1,2,3,4}$.

(3) $s \neq r^i$.

For $r^i$, we go clockwise from 1 by $2\pi/n$ and reach to 2. But with $s$, we have to go
counterclockwise $2\pi/n$ to reach 2.

(4) $sr^{i} \neq sr^j$.

If $sr^i = sr^j$, then $r^i=r^j$. From (1), we have contradiction.

(5) $rs = sr^{-1}$

$s(1) = 1, rs(1) = r(1) = 2$
$s(2) = n, rs(2) = r(n) = 1$
$sr^{-1}(1) = s(n) = 2$
$sr^{-1}(2) = s(1) = 1$

Because these 2 symmetries are the same on 1 and 2, they are the same for all n.

(6) $r^is = sr^{-i}$

$$
r^{i+1}s = r(r^{i}s) = r(sr^{-i}) = (rs)(r^{-i}) = sr^{-1}r^{-i} = sr^{-(i+1)}
$$

* **_2.1.1 Early introduction of generators:_**: if $S \subset G$ and every element of $G$
can be represented as the product of elements of $S$, we say $S$ generates $G$ or $G = <S>$

* ex01

(a) $D_6 = \{1, r, r^2, s, sr, sr^2\}$

(i) $r^3=1, |r|=3$
(ii) $(r^2)^2=r^4=r \neq 1, (r^2)^3=r^6=r^3r^3=1$
(iii) $s^2=1$
(iv) $(sr)^2=(sr)(sr)=s(rs)r=s(sr^{-1})r=s^2=1$
(v) $(sr^2)^2=(sr^2)(sr^2)=s(r^2s)r^2=s(sr^{-2})r^2=1$

(b) $D_8 = \{1, r, r^2, r^3, s, sr, sr^2, sr^3\}$

(i) $r^4=1$
(ii) $(r^2)^2=r^4=1$
(iii) $(r^3)^2=r^6=r^2,(r^3)^3=r^9=r,(r^3)^4=r^12=1$
(iv) The orders of $s, sr, sr^2, sr^3$ are all 2.

* ex02

(a) Let $x = sr^n$, then $r(sr^n) = (rs)r^n = (sr^{-1})r^n = sr^nr^{-1} = xr^{-1}$

* ex03

(a) Let $x = sr^n$, then $x^2 = (sr^n)(sr^n) = s(r^ns)r^n=s(sr^{-n})r^n=1$
(b) Because $r = s(sr)$, then every $r^i,sr^i$ can be represented by $s,sr$.

* ex04

(a) $n = 2k \ge 4$, then $x^2 = (r^k)^2=r^n=1$.
(b) Let $y=sr^i$, then $xy = r^k s r^i = s r^{-k}r^i = s r^k r^i = sr^ir^k=yx$, so $x$
    commutes with all elements in $D_{2n}$.
(c) Assume $sr^i$ communtes, then
    $sr^jsr^i = ssr^{-j}r^i=r^{i-j}$, and $sr^isr^j = r^{j-i}$. But $r^{i-j}=r^{j-i}$ if and
    only if $i-j=k$ based on ex1.1.33
(d) Assume $r^i$ communtes, then
    $r^isr^j = sr^{j-i} = sr^{j+i}$, then we have $r^i = r^{-i}$, so $i=k$.

* ex05

(a) We first prove $sr^i,i>0$ don't commute. $sr^is=ssr^{-i}=r^{-i}$, and $ssr^i=r^i$. So we have $r^{i}=r^{-i}=r^{n-i}$.
since $i > 0$, then $i = n-i$, we have contradiction.
(b) Then we prove $s$ don't commute. Just use $ssr = r \neq r^{-1} = srs$.
(c) Then we prove $r^i, i > 0$. $sr^i\neq sr^{-i} = r^is$.

* ex06

(a) $x^2=1$ so $x=x^{-1}$. Same thing for $y$.
(a) $t=xy$, so $tx = xyx$.
(b) $xt^{-1} = x(xy)^{-1}=x(y^{-1}x^{-1})=xyx$
    