---
title: "Notes-on-Algebra-Notes-from-the-Underground"
author: "Yang Ge"
date: "2/5/2022"
output:
  html_document:
    keep_md: false
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 The Integers

## 1.1 The Well-Ordering Principle and Induction

***definition 1.1*** Let $a, b ∈ Z$. We say that ‘b divides a’, or ‘b is a divisor of a’, or ‘a is a multiple of b’, and write $b | a$, if there is an integer $c$ such that $a = bc$.
 
***lemma1.2*** If $b|a$ and $a \ne 0$,then $|b|≤|a|$.

***FACT (Well-ordering principle)*** Every nonempty set of nonnegative integers
contains a least element.

Next

## 1.2

## 1.3 Greatest Common Divisors

***definition 1.5*** Let $a, b ∈ \mathbb{Z}$. We say that a nonnegative integer $d$ is the ‘greatest common divisor’ of a and b, denoted $\gcd(a, b)$ or simply $(a, b)$, if

* $d | a$ and $d | b$ and
* if $c | a$ and $c | b$, then $c | d$.

* Notes: for the 2nd part, not to use $c \le d$.

***theorem 1.8*** Let $a, b$ be integers. Then the greatest common divisor $d = \gcd(a, b)$ is an integer linear combination of $a$ and $b$. That is, there exist integers $m$ and $n$ such that $d = ma + nb$.

In fact, if $a$ and $b$ are not both 0, then $\gcd(a, b)$ is the smallest positive linear combination of $a$ and $b$.

* Sketch of proof: Use the well-ordering principle.

***corollary 1.9*** Let $a, b$ be integers. Then $\gcd(a, b) = 1$ if and only if 1 may be expressed as a linear combination of $a$ and $b$.

***definition 1.10***  We say that a and b are relatively prime if $\gcd(a, b) = 1$.

***corollary 1.11*** Let $a, b, c$ be integers. If $a | bc$ and $\gcd(a, b) = 1$, then $a | c$.

***theorem 1.14 (Euclidean algorithm)*** Let $a, b$ be integers, with $b \ne 0$. Then, with notation as above, $\gcd(a, b)$ equals the last nonzero remainder $r_n$.

***lemma 1.15*** Let $a, b, q, r$ be integers, with $b \ne 0$, and assume that $a = bq + r$. Then $\gcd (a, b) = \gcd (b,r)$.

Proof. Assume $\gcd (a, b) = r'$, then $r' | r$. And assume $\gcd (b,r) = r''$, then $r'' | a$, so $r'' | r'$. On the other hand $r' | r''$, so $r' = r''$.

The textbook's approach is also clean, it shows the $a,b$ and $b,r$ have
the same set of common divisor.

## 1.4 The Fundamental Theorem of Arithmetic

***definition 1.17*** An integer $p$ is ‘irreducible’ if $p \neq ±1$ and the only divisors of $p$ are $±1, ±p$. An integer $\neq 0$,  $\neq ±1$ is ‘reducible’ or ‘composite’ if it is not irreducible.

***lemma 1.18*** Assume that $p$ is an irreducible integer and that $b$ is not a multiple of $p$. Then $b$ and $p$ are relatively prime, that is, $\gcd(p, b) = 1$.

Proof. Assume $c | p$ and $c | b$, because $p$ is irreducible, then $c = ±1, ±p$. Since $p \nmid b$, then $c$ can only be 1.

***definition 1.19*** An integer $p$ is ‘prime’ if $p \ne ±1$ and whenever $p$ divides the product $bc$ of two integers $b$, $c$, then $p$ divides $b$ or $p$ divides $c$.

***theorem 1.21*** Let $p ∈ Z$, $p \ne 0$. Then $p$ is prime if and only if it is irreducible.

Proof. Assume $p$ is prime and if $a | p$, so $p = ab$, then $p | a$ or $p | b$. Assume $p|a$, then $a = \pm p$. If $p | b$, then $a = \pm1$. So $p$ is
irreducible.

On the other hand, if $p$ is irreducible and assume $p | bc$. Consider
$\gcd(p, b)$. If $\gcd(p, b) = 1$, then $p | c$. If $\gcd(p, b) = p$, then
$p | b$.

***theorem 1.22***  (Fundamental Theorem of Arithmetic) Every integer $n \ne 0,  ±1$ is
a product of finitely many irreducible integers: $∀n ∈ Z, n \ne 0, n \ne ±1$, there exist
irreducible integers $q_1,..., q_r$ such that

$$
n = q_1 ··· q_r
$$
Proof: The existence, use contradiction and well-ordering principle.
Assume $n$ is the smallest integer that cannot be a product of irreducible integers. And $n$ cannot be irreducible itself. So assume $n = ab$, because
$n$ is the smallest such integer, $a, b$ must be a product of irreducible integers. So we have a contradiction.

The uniqueness, again use contradiction and well-ordering principle.
Assume $n$ is the smallest integer such that it has two different
factorization.
$$
n = q_1 ··· q_r = p_1 ... p_s
$$
Because $q_1$ is prime, so $q_1 | p_1$, but $p_1$ is irreducible, so
$q_1 = p_1$. So

$$
n = q_1 ··· q_r = q_1 ... p_s
$$
And let

$$
m = q_2 ... q_r = p_2 ... p_s
$$

$m < n$ and it has two different factorization. We have a contradiction.

* We will see later $\mathbb{Z}$ is a UFD (‘unique factorization domain’).

***proposition 1.25*** Let a, b be nonzero integers, and write

$$
a = 2^{\alpha_2} 3^{\alpha_3} \cdots \\
b = 2^{\beta_2} 3^{\beta_3} \cdots \\
$$

Then the gcd of $a$ and $b$ is the positive integer

$$
d = 2^{\delta_2} 3^{\delta_3} \cdots \\
$$
where $\delta_i = \min(\alpha_i, \beta_i)$.

Proof: If 

$$
c = 2^{\gamma_2} 3^{\gamma_3} \cdots
$$

is a commond divisor. Then $\gamma_i \le \min(\alpha_i, \beta_i) = \delta_i$.
So $c | d$.

* least common multiple (lcm) is similarly obtained by taking exponents $\max(α_i, β_i)$. (The ‘least common multiple’ of $a$
and $b$ is what it says it should be: a number that is a multiple of $a$ and a multiple of $b$,
and such that every common multiple of $a$ and $b$ is a multiple of $l$.)

***corollary 1.27*** Two nonzero integers a, b are relatively prime if and only if they have no common irreducible factor.

## Exercises

***1.2*** ◃ Prove that divisibility is an order relation on the set $Z^{≥0}$ of nonnegative integers. That is, prove that for all positive integers a, b, c:

(i) $a|a$;
(ii) if $a|b$ and $b|c$,then $a|c$;
(iii) if $a|b$ and $b|a$ ,then $a=b$.

Is this order relation a total ordering? Does it have a ‘maximum’? (That is, is there an integer $m$ such that $∀a ∈ Z^{≥0}, a | m?)$

Proof: 

(i) $a = a \cdot 1$
(ii) $b = aa_0, c = bb_0$, so $c = aa_0b_0$. So $a | c$
(iii) From lemma 1.2, $a | b$, so $a \le b$. $b | a$, so $b \le a$. So $a = b$.

This is not a total ordering. Consider $a = 2, b = 3$, $a \nmid b$ and $b \nmid a$.
$0$ is a maximum.

***1.8*** ◃ Let $n$ be a positive integer, and let $a$ and $b$ be integers. Prove that $a$ and $b$ have
the same remainder when divided by $n$ if and only if $a − b = nk$ for some integer $k$.

Proof:

if $a − b = nk$, let $a = pn+r, b = qn+s$, then $pn+r = qn+s+kn$.
So
$$
r - s = (p-q-k)n
$$
So $n \mid r-s$. Because $0 \le r, s<n$, so $|r-s| < n$, we must have $r = s$.

On the other hand, if $r = s$, then $a - b = (p - q)n$.

***1.10*** ◃Suppose $\gcd(a,b)=1$. Prove that if $a|c$ and $b|c$,then $ab|c$.

Proof: Since $\gcd(a,b)=1$, we have $ma + nb = 1$. Also assume
$c = ap, c = bq$, then $c = mac + nbc = mabq + nbap = (mq+np)ab$.
So $ab | c$.

***1.11*** Prove that if $a|(b+c)$ and $\gcd(b,c)=1$,then $\gcd(a,b)=1$.

Proof:

$$
b+c = pa, \\
1 = mb + nc, \\
1 = mb+n(pa-b) = (m-n)b + npa.
$$
***1.12*** Prove that if $\gcd(a, c) = 1$ and $\gcd(b, c) = 1$,
then $\gcd(ab, c) = 1$.

Proof:

$$
1 = ma + nc, \\
1 = pb + qc, \\
1 = (ma + nc)(pb + qc) = mpab + (maq+npb+nqc)c
$$
***1.13*** Prove that if $\gcd(a, b) = 1$, then $\gcd(a^r, b^s) = 1$ for all positive integers $r, s$.

Proof: From 1.12, we know $\gcd(a, b) = 1$, so $\gcd(a^2, b) = 1$.
Then using induction, we can prove $\gcd(a^r, b) = 1$ for all $r$.
Then using 1.12 again, we can prove $\gcd(a^r, b^2) = 1$.
Then using induction again, we can prove $\gcd(a^r, b^s) = 1$

***1.14*** Prove that if $c > 0$, then $\gcd(ca, cb) = c · \gcd(a, b)$.

Proof. Assume $\gcd(ca, cb) = e$, $d = \gcd(a, b)$, then $cd | ca$ and $cd | cb$ so $cd | e$.
Now it's clear $c | e$, then assume $e = cd'$, then $d' | a$ and $d' | b$,
so $d' | d$. So $e = cd' | cd$, so $\gcd(ca, cb) = e = cd$.

***1.15*** Prove that if $c | ab$ and $\gcd(a, c) = d$, then $c | db$.

Proof. Assume $a = dm$ and $c = dn$ and $\gcd(m, n) = 1$.
Then $n | mb$, so from corollary 1.11, we know $n | b$.
So $c = dn | db$.

***1.16*** Obvious, skip

***1.17***  Prove that if $p$ is prime, and $p$ divides a product of integers $a_1 ··· a_s$, then
$p$ divides one of the integers $a_i$. (Try induction, or another use of the well-ordering principle.)

Proof. Let $m$ be the smallest integer such that $p | a_1 \cdots a_m$, but
$p \nmid a_i$. Then $p | a_1 \cdots a_{m-1}$, then we have a contradiction.

***1.18*** Let $p \ne 0, ±1$ be an integer. Prove that $p$ is prime if and only if for all $a ∈ Z$, either $p | a$ or $\gcd(a, p) = 1$.

Proof. Assume $p$ is prime. And $\gcd(a, p) = b$, then $p = bq, a = ba'$.
Then $p | qa=bqa'$. If $p | q$, then $b = 1$. Otherwise $p | a$.

Conversely, assume $p | ab$, if $p \nmid a$, then $\gcd(a, p) = 1$.
According to corollary 1.11, $p | b$. Then $p$ is prime.

***1.19*** Prove that if $p$ is prime, $a, n ∈ Z$, with $n ≥ 0$, and $p | a^n$, then $p^n | a^n$.

Proof. $p$ is prime, and $p| a^n$, then based onex 1.17 so $p | a$.
Assume $a = pq$ then $a^n = (pq)^n$, so $p^n | a^n$.

***1.21*** 

$$
n = 2^{v_2} 3^{v_3} 5^{v_5} 7^{v_7} 11^{v_{11}} ··· \\
c = 2^{r_2} 3^{r_3} 5^{r_5} 7^{r_7} 11^{r_{11}} ···
$$

Proof. Assume $c | n$, and $r_p > v_p$ for some $p$.
$$
n = p^{v_p} n' \\
c = p^{r_p} c' \\
$$

$p \nmid n'$, but $c | n$, we have $p^{r_p - v_p} | n'$ we have a contradiction.

The solution is cleaner.

***1.23*** Let $a, b$ be positive integers. Prove that $\gcd(a, b) \text{lcm}(a, b) = ab.$

Proof

$$
\gcd(a, b) \text{lcm}(a, b) = \\
2^{\min(a_2, b_2)} 3^{\min(a_3, b_3)} \cdots
2^{\max(a_2, b_2)} 3^{\max(a_3, b_3)} \cdots = \\
2^{\min(a_2, b_2) + \max(a_2, b_2)} 3 ^{\min(a_3, b_3) + \max(a_3, b_3)} = \\
2^{a_2+b_2} 3^{a_3+b_3} \cdots = a b
$$
***1.24*** Let $a, b ∈ Z$, and assume that $\gcd(a, b) = 1$ and that $ab$ is a perfect square (that
is, $ab = n^2$ for some integer $n$). Prove that $a$ and $b$ are perfect squares.

Proof.

$$
a = 2^{\alpha_2} 3^{\alpha_3} \cdots \\
b = 2^{\beta_2} 3^{\beta_3} \cdots \\
$$
Then $(\alpha_i + \beta_i)$ is even. Since $\gcd(a, b) = 1$, then either
$\alpha_i$ or $\beta_i$ is even, then both of them are even.
So both $a$ and $b$ are perfect squares.

***1.25***  Let $p > 0$ be an irreducible integer. Prove that $\sqrt{p}$ is irrational. (Hint: If not,
then $\sqrt{p} = a/b$ for some integers a and b. This implies $a^2 = pb^2$. What does the Fundamental Theorem tell you in this case?)

Proof:

$$
a = 2^{\alpha_2} 3^{\alpha_3} \cdots p^{\alpha_p} \cdots \\
b = 2^{\beta_2} 3^{\beta_3} \cdots p^{\beta_p} \cdots \\
$$
Then we have $2 \alpha_p = 1 + 2 \beta_p$, which is not possible.

# 2 Modular Arithmetic

pg 40 - 58

## 2.1 Equivalence Relations and Quotients
## 2.2 Congruence mod $n$

***definition 2.1*** Let $n ≥ 0$ be an integer, and let $a, b ∈ Z$x. We say that '$a$ is congruent to $b$ modulo $n$', denoted $a ≡ b$ mod $n$, if $b − a ∈ nZ$.

$$
a \equiv b \mod n \iff n | b - a
$$

* For any nonnegative integer $n$ and any integer $a$,
we denote by $[a]_n$ the equivalence class of $a$ with respect to the relation of congruence
modulo $n$. Explicitly:

$$
[a]_n = \\
\{b \in \mathbb{Z} | a \equiv b \mod n\} = \\
\{b \in \mathbb{Z} | n \text{ divides } b - a\} = \\
\{b = a + nk | k \in \mathbb{Z} \}
$$

***definition 2.5*** For any integer $n ≥ 0$ we denote by $\mathbb{Z}/n\mathbb{Z}$ the set of congruence classes
mod $n$ in $\mathbb{Z}$. This set is called the ‘quotient of $\mathbb{Z}$ modulo $n\mathbb{Z}$’, or simply ‘$\mathbb{Z}$ mod n’.

***lemma 2.6***  Let $n$ be a positive integer.

* Let $a \in \mathbb{Z}$, and let $r$ be the remainder after division of $a$ by $n$. Then $[a]_n = [r]_n$.
* The classes $[0]_n, \dots, [n-1]_n$ are all distinct.

Proof. Assume $a = qn + r$, then $a - r = nq$, so $n | a - r$. Then
$a \equiv r \mod n$. So $[a]_n = [r]_n$.

Assume $[i]_n = [j]_n$ and $0 \le i, j \le n-1$, then $n | i - j$.
Then we have $i = j$.

***theorem 2.7*** For all positive integers n, the set Z/nZ consists of exactly n elements: $[0]_n, \dots, [n-1]_n$.

***Remark 2.8***  If $n = 0$, we can still make sense of the quotient, i.e., of $\mathbb{Z}/0\mathbb{Z}$. the equivalence class $[a]_0$ of
an integer $a$ consists of the single element $a$: $[a]_0 = \{a\}$.
Therefore, the set $\mathbb{Z}/0\mathbb{Z}$ is just a copy of $\mathbb{Z}$ itself.

## 2.3 Algebra in $\mathbb{Z}/n\mathbb{Z}$

***lemma 2.9*** Let $n ≥ 0$ be an integer, and let $a, a', b, b'$ be integers.

(i) $a+b \equiv a'+b' \mod n$
(ii) $a\cdot b \equiv a' \cdot b' \mod n$

***definition 2.10*** Let $n ≥ 0$ be an integer, and let $[a]_n, [b]_n$ be elements of $\mathbb{Z}/n\mathbb{Z}$. We define

$$
[a]_n + [b]_n := [a + b]_n , \\
[a]_n · [b]_n := [a · b]_n .
$$

* What do we learn from this example (example 2.11)?
    * We would say that the operation we just tried to define on our     
    equivalence classes $[a]_∼$ is not well-defined.
    * It is not a viable 
    definition, because the outcome of the operation depends on how we choose
    to write our elements.
    * Whether you decide to call the first class
    $[0]_∼$ or $[−2]_∼$ cannot affect the result of an
    operation depending on this class: the operation should depend on the
    class itself, not on your mood of the moment on how you decide to call 
    the class.

## 2.4 Properties of the Operations +, · on $\mathbb{Z}/n\mathbb{Z}$

***theorem 2.13*** For every positive integer $n$, all of these properties hold for $\mathbb{Z}/n\mathbb{Z}$ with $0 = [0]_n$ and $1 = [1]_n$.

***theorem 2.15*** Let $n > 1$. Then the following assertions are equivalent:

(i) The integer n is prime.
(ii) In $\mathbb{Z}/n\mathbb{Z}$, property (2.2) is satisfied: $∀a, b, ab = 0 \implies a = 0 \text{ or } b = 0$.
(iii) In $\mathbb{Z}/n\mathbb{Z}$, property (2.4) is satisfied: if $a \ne 0$, then $a$ has a multiplicative inverse.

Proof. 

(i) $\implies$ (ii). If $n$ is prime and $n | ab$, then $n | a$ or $n | b$.
So $a = 0 \text{ or } b = 0$.

(ii) $\implies$ (iii). Assume $ab = ab'$, then $a(b-b')=0$, then $b = b'$.
Then $ab \ne ab'$ if $b \ne b$. So $ab$ is different for all $0, n-1$.
There must be some $b$, such that $ab=1$.

(iii) $\implies$ (i). Assume $a | n$, and $ab = 1$. Then. $n | ab-1$, then
$a | ab - 1$, then $a | 1$. So $a = 1$. Then $n$ is irreducible and thus prime.

(i) $\implies$ (iii). If $n$ is prime, then $\gcd(a, n) = 1$. So
$ab + nq = 1$. So $n | nq = ab - 1$. So $ab = 1$.

(iii) $\implies$ (ii). $n | ab$, $n \nmid a$. Let $a' = \gcd(a, n)$, since $a'b' = 1$,
then $a' | a'b'-1$, so $a' | 1$, then $a' = 1$.
Then $n | b$.

(ii) $\implies$ (i) This is the definition of prime.

***proposition 2.16*** Let $n > 1$ be an integer. Then a class $[\mathcal{l}]_n$ has a multiplicative
inverse in $\mathbb{Z}/n\mathbb{Z}$ if and only if $\gcd(n, l) = 1$.

Proof.
If $[l]_n$ has a multiplicative inverse, then assume $al = 1$.
So if $\gcd(n, l) = b$, then $b | n$, so $b | n | al - 1$, and $b | l$,
so $b | 1$. So $b = 1$.

We can also use corollary 1.9

Conversely, if $\gcd(n, l) = 1$, we can find $an + bl = 1$, so $[b]_n[l]_n = 1$. Then $[l]_n$ has a multiplicative inverse.

* So in theorem 2.15, why do we need to have make sure $n \ne 0$. Because
when we prove (i) $\implies$ (iii), we use such argument:
If $n$ is prime, then $\gcd(a, n) = 1$. It's not true when $n=0$.

## 2.5 Fermat’s Little Theorem, and the RSA Encryption System

***theorem 2.18 (Fermat’s little theorem)*** Let $a, p$ be integers, with $p$ positive and prime. Then $[a]_p^p = [a]_p$ or $a^{p-1} \equiv 1 \mod p$.

Proof.

$$
[a]_p, [2a]_p, \cdots, [(p-1)a]_p
$$

are all different. Then

$$
[a]_p \cdot [2a]_p \cdot [(p-1)a]_p = [1]_p [2]_p \cdots [p-1]_p
$$

So $a^{p-1} = 1$.

***theorem 2.19 (RSA algorithm)*** Let $p, q$ be positive prime integers, and let 

$$
n = pq \\
k = (p-1)(q-1) \\
\gcd(e, k) = 1 \\
de \equiv 1 \mod k \\
a \\
b \in [a]_n^e 
$$

We have $a \equiv b^d \mod n$.

Proof. Since $b^d \equiv a^{ed} \mod n$, we just need to prove $a \equiv a^{ed} \mod n$. Since $ed = kr + 1$, we just need to show
$a^{kr} \equiv 1 \mod n$.

We first will show $a ^{kr} \equiv 1 \mod p$, this is because
$a^{p-1} \equiv 1 \mod p$, then $a^{(p-1)(q-1)r} \equiv 1 \mod p$.
Similarly, we can prove $a ^{kr} \equiv 1 \mod q$.

And therefore $a ^{kr} \equiv 1 \mod n$.

## Exercise

Solution is in pg 422

2.1 Prove that if $a ≡ b \mod n$ and $k | n$, then $a ≡ b \mod k$.

Proof. $n | a - b$ and $k | n$, then $k | a - b$. Then $a ≡ b \mod k$.

2.2 Prove that if $a ≡ b \mod q$ for all positive irreducible integers $q$, then $a = b$.

Proof. consider $n = a - b$, since there exists infinit many irreducible integers, we can find $q > n$ and $q$ is irreducible. Since $q | n$, then
$n = 0$, and $a = b$.

2.3 Prove that if $q ≥ 5$ and $q$ is irreducible, then $[q]_6 = [1]_6$ or $[q]_6 = [5]_6$.

Proof. Because it cannot be $[0]_6, [2]_6, [3]_6$. Then would mean $6 | q$
or $2 | q$ or $3 | q$.

2.4  Find a proof or a counterexample of the following statement: If 
$[a]_n \ne [0]_n$, and
$[a]_n[b]_n = [a]_n[c]_n$, then $[b]_n = [c]_n$.

counterexample: Let
$$
[a]_n = [2]_6 \\
[b]_n = [1]_6 \\
[c]_n = [4]_6 \\
$$

2.5 Find a class $[a]_{99} \ne [0]_{99}$ in $\mathbb{Z}/99\mathbb{Z}$ such that there is no integer $b$ for which
$[a]_{99}[b]_{99} = [1]_{99}$.

Solution: for example let $a = 3$. Because $3 | 3b - 99q$, $3b \not\equiv 1 \mod 99$.

2.6 Assume that $[a]_n = [1]_n$. Prove that $\gcd(a, n) = 1$.
Find an example showing that the converse is not true.

Proof. $a - 1 = kn$, then $1 = a - kn$. Assume $\gcd(a, n) = b$,
then $b | a$, $b | n$, then $b | a - kn = 1$. So $b = 1$.

Conversely, let $a = 2, n = 5$, $[2]_5 \ne [1]_5$, but $\gcd(2,5) = 1$.

2.7 Prove that every positive integer is congruent modulo 9 to the sum of its digits.

Proof. 

$$
a_n\cdots a_1 a_0 = 10^na_n + \cdots + 10 a_1 + a_0 \\
= (9+1)^na_n + \cdots (9+1)a_1 + a_0 \\
= (9b_n+1)a_n + \cdots (9+1)a_1 + a_0 \\
= 9K + (a_n + \dots + a_1 + a_0)
$$

2.8  Find the last digit of $7^1000000$.

Solution: it's $7, 9, 3, 1, 7, 9, 3, 1, \dots$, so it's 1.

2.9  Find a congruence class $[a]_7$ in $\mathbb{Z}/7\mathbb{Z}$ such that every class $[b]_7$ except $[0]_7$ equals a power of $[a]_7$.

Solution: 

$$
2, 4, 1, 2 \\
3, 2, 6, 4, 5, 1, 3\\
4, 2, 1, 4 \\
5, 4, 6, 2, 3, 1, 5\\
6, 1, 6
$$

2.10  Let $n > 0$ be an odd integer that may be written as the sum of two perfect
squares. Prove that $[n]_4 = [1]_4$.

$$
n = n_1^2 + n_2^2 = (2k_1)^2 + (2k_2+1)^2 = 4K + 1  
$$

2.11  Prove that for all $a ∈ \mathbb{Z}/n\mathbb{Z}$, $a · 0 = 0$ (where 0 stands for $[0]_n$).

Proof: $a \cdot n \cdot q \equiv 0 \mod n$.

2.12 Let $p > 0$ be a prime integer, and let $a ∈ \mathbb{Z}/p\mathbb{Z}$,
$a \ne 0$. Prove that the multiplica-
tive inverse of a, whose existence is guaranteed by Theorem 2.15, is unique.

Proof:

$b = (b'a)b = b'(ab) = b'$.

2.14 Let $a, b, n$ be integers, with $n > 0$, and assume $\gcd(a, n) = 1$. Prove that the equation $[a]_n x = [b]_n$ has a unique solution in $\mathbb{Z}/n\mathbb{Z}$.

Proof. $\gcd(a, n) = 1$, then $ac+ny=1$, then we have $acb+nyb=b$.
So $acb \equiv b \mod n$. So let $x = [cb]_n$.

Now assume $[a]_n x' = [b]_n$, then we have $[a]_n (x - x') = 0$.
Then we have $n | a (x- x')$, and we have $n | x - x'$.
So $x \equiv x' \mod n$.

2.15 Let $p > 0$ be a prime integer. Prove that the equation $x^2 + x = 0$ has exactly two solutions in $\mathbb{Z}/p\mathbb{Z}$, and find those solutions.

Proof. the two solutions are $0, p-1$.

2.16 Let $n > 0$ be an integer, and let $a, b ∈ \mathbb{Z}/n\mathbb{Z}$. Assume that both $a$ and $b$ have
multiplicative inverses. Prove that $ab$ has a multiplicative inverse.

Proof. It's $b^{-1}a^{-1}$.

2.17 Let $n > 0$ be an integer, and let $a ∈ \mathbb{Z}/n\mathbb{Z}$.
Prove $a$ has a multiplicative inverses or there exists a
$b∈\mathbb{Z}/n\mathbb{Z}$, $b \ne 0$, such that $ab = 0$.

Proof. Consider $1 \cdot a, 2 \cdot a, \cdots, (n-1)a$. Then two of them
must be equal.

2.18  Prove that the two formulations of Fermat’s little theorem are equivalent.

Proof. If $a^p \equiv a \mod p$, then $a^p-a = a(a^{p-1} - 1) = 0$.
Since $a\ne 0$, then $a^{p-1} \equiv 1 \mod p$.

If $a^{p-1} = 1$, then $a \cdot a^{p-1} = a$, then $a^p = a$.

2.20  Let $n, a, b_1,..., b_r$ be integers, with $n > 1$ and $1 < a < n$, $1 < b_i < n$. Assume that $a$ is a witness to the fact that $n$ is composite
(that is, $a^{n−1} \not\equiv 1 \mod n$) and that
$\gcd(a, n) = 1$.

Prove that if $b_i$ is not a witness, then $ab_i$is a witness.

Proof. $(ab_i)^n \equiv a^n b_i^n \equiv a^n \not\equiv 1 \mod n$.

Prove. Prove that if $[b_1]_n,..., [b_r]_n$ are all different, then so are $[ab_1]_n,..., [ab_r]_n$.

Proof. Assume $a(b_1 - b_2) = 0$, then $n | a(b_1 - b_2)$. Since
$\gcd(a, n) = 1$, then $b_1 = b2$. So $[ab_1]_n,..., [ab_r]_n$ are all different.

Deduce that in this case $n$ has fewer than $n/2$ non-witnesses.

Proof. Assume $[b_1]_n,..., [b_r]_n$ are all non-witnesses and they
are all different.
$[a]_n, [ab_1]_n,..., [ab_r]_n$ are all different. So the $r < n/2$.

2.21 A composite number $n$ is a Carmichael number if $a^{n−1} ≡ 1$ modulo $n$ for all $a$ relatively prime to $n$.

Prove that if $n$ is a square-free integer (that is, $n$ is not a multiple of a perfect square)
such that $p − 1$ divides $n − 1$ for all prime factors $p$ of $n$, then $n$ is a Carmichael number.

Proof. 

Since $n$ is a square-free integer, then $n = p_1\cdots p_k$.
Assume $p_1 | n$ and is a prime number. We prove $p_1 | a^{n-1} - 1$.
This is because $a^{p_1-1} \equiv 1 \mod p_1$, and $p_1-1 | n-1$.
So $a^{n_1-1} \equiv 1 \mod p_1$. We are done.

# 3 Rings

## 3.1 Definition and Examples

***definition 3.1*** A ‘ring’ $(R, +, ·)$ consists of a set $R$ along with two binary operations
$+$ and $·$ (called ‘addition’ and ‘multiplication’), satisfying the following properties.

(i) Associativity for addition: $\forall a,b,c \in R, (a+b)+c = a+(b+c)$ 
(ii) Existence of additive identity:
(iii) Existence of additive inverses:
(iv) Commutativity for addition:
(v) Associativity for multiplication: $\forall a,b,c \in R, (a \cdot b) \cdot c = a \cdot (b \cdot c)$
(vi) Existence of multiplicative identity:
$∃1_R ∈ R, ∀a ∈ R, a · 1_R = 1_R · a = a$

(vii) Distributivity:

$$
∀a, b, c ∈ R \\
a\cdot(b + c) = a \cdot b + a \cdot c \\
$$

***Example 3.2*** $\mathbb{Z}$ is a ring.

***Example 3.3*** The sets $\mathbb{Q}$, $\mathbb{R}$, and $\mathbb{C}$ of rational, real, and complex numbers form rings
with the usual operations.

***Example 3.4*** For every nonnegative integer $n, \mathbb{Z}/n\mathbb{Z}$ is a ring.

***Example 3.6*** Another non-example, for more serious reasons: Consider the set
$\mathbb{N} = Z^{≥0}$ of natural numbers. With the usual operations +, ·, N satisfies all the ring axioms
with the exception of the existence of additive inverses, axiom (iii): for instance, there
is no $a ∈ \mathbb{N}$ such that $1 + a = 0$. (Such a would be −1, and −1 is not an element of $\mathbb{N}$.)
Thus, $\mathbb{N}$ is not a ring. As it happens, axiom (iii) is so fundamental that nobody on this
planet calls $\mathbb{N}$ a ring.

***Example 3.7*** Another non-example! The set $Z≤0$ of ‘nonpositive numbers’ is even
worse off than $\mathbb{N}$, since (−1) · (−1) = 1  $Z≤0$: the set $Z≤0$ is not closed with respect
to (ordinary) multiplication. Thus, we do not even know how to interpret the last three
axioms in the list, for this set (at least if we stick to the ordinary operations).

***Example 3.8*** A ring $R$ cannot be empty: axioms (ii) and (vi) prescribe the existence of
some elements in $R$, so $R = ∅$ is not an option. How small can $R$ be?
In the trivial ring $0_R$ and $1_R$
both equal $r$: there is no room for anything else. So $0 = 1$ in the trivial ring.

***Example 3.9*** Consider the set $M_{2,2}(\mathbb{R})$ of 2 × 2 matrices with entries in $\mathbb{R}$. Also  $M_{2,2}(\mathbb{Z}/2\mathbb{Z})$.
Also $M_{2,2}(M_{2,2}(\mathbb{Z}))$

***Example 3.10***  Another class of examples with which you are already familiar is given by polynomials.
(i) $R[x]$
(ii) $\mathbb{R}[x]$
(iii) $R[x_1, \dots, x_n]$

## 3.2 Basic Properties

***proposition 3.14*** Let $R$ be a ring. Then $1$ and $0$ are unique.

***proposition 3.15*** Let $R$ be a ring, and let $a$ be an element of $R$. Then the additive inverse of $a$ is unique.

***proposition 3.17*** Let $R$ be a ring, and let $a, b, c ∈ R$. Assume that $a + b = a + c$. Then $b = c$.

Proof. 

$$
b = b + (a + (-a)) = (b + a) + (-a) = (c + a) + (-a) = c 
$$

***corollary 3.18*** Let $R$ be a ring, and let $a ∈ R$. Then $0 · a = a · 0 = 0$.

Proof.

$$
0 \cdot a + 0 \cdot a = (0 + 0) \cdot a = 0 \cdot a + 0
$$

So $0 \cdot a = 0$.

## 3.3 Special Types of Rings

***definition 3.20*** A ‘commutative ring’ is a ring $R$ in which multiplication is commutative, that is, in which the property

$$
∀a, b ∈ R, ab = ba
$$

holds.

***Example 3.21*** In the ring $\mathbb{Z}/10\mathbb{Z}$, $[2]_{10} · [5]_{10} = [0]_{10}$ even though $[2]_{10} \ne [0]_{10}$ and
$[5]_{10} \ne [0]_{10}$.

***definition 3.22*** Let $R$ be a ring. We say that $a ∈ R$ is a ‘zero-divisor’ if there exists a nonzero $b ∈ R$ such that $ab = 0$ or $ba = 0$.

***definition 3.23*** Let $R$ be a commutative ring. Then $R$ is an ‘integral domain’ if

$$
∀a, b ∈ R ab = 0 \implies a = 0 \text{ or } b = 0
$$

and $0 \ne 1$ in $R$.

***Example 3.24*** In fact, we have seen an inkling of this relation already. We have proved that (3.7) holds for the ring $\mathbb{Z}/n\mathbb{Z}$ if and only if $n$ is a prime integer: see Theorem 2.15 for $n > 1$; and $\mathbb{Z}/0\mathbb{Z}$ is an integral domain because $\mathbb{Z}$ is.

***proposition 3.26*** Let $R$ be a ring, and let $a ∈ R$. If $a$ is a non-zero-divisor, then
multiplicative cancellation holds for $a$, in the sense that

$$
∀b, c ∈ R, ab = ac \implies b = c \text{ and } ba = ca \implies b = c .
$$

In particular, if $R$ is an integral domain, then multiplicative cancellation holds for
every nonzero element of $R$.

***definition 3.27*** An element $b$ of a ring $R$ is a ‘multiplicative inverse’ of an element
$a ∈ R$ if $ab = ba = 1_R$. If $a ∈ R$ has a multiplicative inverse (in $R$), then it is said to be
‘invertible’, or a ‘unit’. The set of units in a ring $R$ is denoted $R^∗$.

***proposition 3.28*** Let $n > 0$ be an integer. Then

$$
(\mathbb{Z}/n\mathbb{Z})∗ =
\{[a]_n ∈ \mathbb{Z}/n\mathbb{Z} | \gcd(a, n) = 1\} .
$$

Proof: Proposition see 2.16.

***definition 3.29*** A ‘field’ is a nontrivial commutative ring $R$ in which every nonzero element of $R$ is invertible, that is:

$$
\forall a \in R, a\ne 0 \implies (\exists b \in R ,  ab = ba = 1)
$$

***Example 3.30*** The reader knows many examples already: $\mathbb{Q}, \mathbb{R}, \mathbb{C}$ are all fields, and
we have proved (Theorem 2.15) that $\mathbb{Z}/p\mathbb{Z}$ is a field whenever p is a positive prime
integer, that is, a positive irreducible number.

***proposition 3.31*** Fields are integral domains.

Proof.

$$
ab = 0, a \ne 0,
a^{-1}ab = 1 b = b = 0
$$

* $\mathbb{Z}$ is not a field.
* $\mathbb{Q}[x]$ is not a field.

***proposition 3.33*** Let $R$ be a finite integral domain. Then $R$ is a field.

Proof. Assume $R = \{ r_1, \dots  r_n \}$, consider


$$
r_1r_1, \dots r_1r_n
$$

if none of them is 1, then $r_1 (r_k - r_j) = 0$, since $r_k - r_j \ne 0$,
then $r_1 = 0$.

## Exercises

pg 75 solution pg 424

***3.1*** Proof. let $a = 5m, b=5m$, $a\odot b = (5a)(5b)/5= 5ab \in 5 \mathbb{Z}$. So it's closed. And the multipliy inverse is $5$ it self.

***3.2*** Define a new ‘multiplication’ operation on $\mathbb{Z}$, by setting $a \odot b = −ab$. Is $(\mathbb{Z}, +, \odot)$
a ring according to Definition 3.1? (Prove it is, or explain why it is not.)

Proof. Yes, it is!

Associativity for multiplication:
$\forall a,b,c \in R, (a \cdot b) \cdot c = a \cdot (b \cdot c)$


$$
(a \odot b) \odot c = (-ab) \odot c = abc \\
a \odot (b \odot c) = a \odot (-bc) = abc
$$

Existence of multiplicative identity:
$∃1_R ∈ R, ∀a ∈ R, a · 1_R = 1_R · a = a$

$$
a \odot (-1) = -(a\cdot-1)=a \\
(-1) \odot a = -(-1\cdot a) = a
$$

(vii) Distributivity:

$$
∀a, b, c ∈ R \\
a\cdot(b + c) = a \cdot b + a \cdot c \\
$$

$$
a \odot (b+c) = -a(b+c) = -ab -ac = a \odot b + a \odot c
$$

***3.3*** Define new operations $\oplus, \odot$ on $\mathbb{Z}$, by setting

$$
a \oplus b = a + b -1, a \odot b  = a + b - ab
$$

Prove that $(\mathbb{Z}, \oplus, \odot)$ is a ring. What are 0 and 1 in this new ring?

Proof.

(i) Associativity for addition: $\forall a,b,c \in R, (a+b)+c = a+(b+c)$ 

$$
(a \oplus b) \oplus c = (a + b - 1) \oplus c = (a + b - 1) + c - 1 = a + b + c - 2 \\
a \oplus (b \oplus c) = a \oplus (b + c - 1) = a + (b + c - 1) - 1 = a + b + c - 2
$$
(ii) Existence of additive identity:

$$
a \oplus 1 = a + 1 - 1 = a
$$

(iii) Existence of additive inverses:

$$
a \oplus b = a + b - 1 = 1 \\
b = 2 - a
$$

(iv) Commutativity for addition:

$$
a \oplus b = a + b - 1 \\
b \oplus a = b + a - 1 \\
$$
(v) Associativity for multiplication: $\forall a,b,c \in R, (a \cdot b) \cdot c = a \cdot (b \cdot c)$

$$
(a \odot b) \odot c = (a + b - ab) \odot c = (a + b - ab) + c - (a + b - ab)c \\
= a + b - ab + c - ac -bc + abc \\
a \odot (b \odot c) = a \odot (b + c - bc) = \\
a + (b + c - bc) - a(b + c - bc) = \\
a + b+ c - bc - ab - ac + abc
$$

(vi) Existence of multiplicative identity:
$∃1_R ∈ R, ∀a ∈ R, a · 1_R = 1_R · a = a$

$$
a \odot b = a + b - ab = a \\
b = 0
$$

(vii) Distributivity:

$$
∀a, b, c ∈ R \\
a\cdot(b + c) = a \cdot b + a \cdot c \\
$$

$$
a \odot (b \oplus c) = a \odot (b + c - 1) = a + (b + c - 1) - a(b + c -1) = \\
a + b + c - 1 - ab - ac + a \\
(a \odot b) \oplus (a \odot c) = (a + b - ab) \oplus (a + c - ac) = \\
(a + b - ab) + (a + c - ac) - 1 = \\
2a + b + c - ab - ac - 1
$$

So this is a ring.

3.4 Let $R = \mathcal{P}(S)$ denote the set of subsets of a set $S$. Define two operations on $R$: for all $A, B ⊆ S$, set

$$
A + B := (A \backslash B) \cup (B \backslash A) \\
A \cdot B := A \cap B
$$
Prove $(R, +, \cdot)$ is a ring.

Proof.

(i) Associativity for addition: $\forall a,b,c \in R, (a+b)+c = a+(b+c)$ 

$$
(A + B) + C = ((A \backslash B) \cup (B \backslash A)) + C = \\
((A\cup B)\backslash (A \cap B)) + C = \\
(((A\cup B)\backslash (A \cap B)) \cup C) \backslash
(((A\cup B)\backslash (A \cap B)) \cap C) \\
= (A \backslash (B \cup C)) \cup
(B \backslash (C \cup A)) \cup
(C \backslash (A \cup B))
$$

(ii) Existence of additive identity:

$$
A + \emptyset = (A \backslash \emptyset) \cup (\emptyset \backslash A)
= A \cup \emptyset = A
$$

(iii) Existence of additive inverses:

$$
A + A = (A \backslash A) \cup (A \backslash A) =
\emptyset \cup \emptyset = \emptyset
$$

(iv) Commutativity for addition: obvious.

(v) Associativity for multiplication:

$$
(A \cap B) \cap C = A \cap (B \cap C)
$$

(vi) Existence of multiplicative identity:

$$
A \cap S = A
$$

(vii) Distributivity:

$$
∀a, b, c ∈ R \\
a\cdot(b + c) = a \cdot b + a \cdot c \\
$$

$$
A \cap (B \backslash C \cup C \backslash B)=
(A \cap B) \backslash (A \cap C) \cup
(A \cap C) \backslash (A \cap B) 
$$

***3.5***  Let $R$ be a ring, and assume that $0 = 1$ in $R$. Prove that $R$ consists of a single element.

Proof. 

$$
a \cdot 0 + a = a \cdot (0 + 1) = a \cdot 1 = a + 0 \\
\text{so } a\cdot 0 = 0
$$

Assume $a \in R$. Then $a \cdot 1 = a \cdot 0 = 0$.

***3.6***  Let R be a ring. Prove that $∀a ∈ R, (−1) · a = −a$.

$$
a + (−1) · a = (1 + (-1)) \cdot a = 0 \cdot a = 0
$$

***3.7*** Let $R$ be a ring, and $a, b ∈ R$. Prove that $−(a + b) = (−a) + (−b)$. Deduce that $(−n)a = −(na)$ equals $n(−a)$ for every nonnegative integer $n$.

Proof. 

$$
(a+b) + ( (−a) + (−b) ) = \\
(a+b + (-a)) + (-b) = \\
b + (-b) = 0
$$

***3.20***  An element $a$ in a ring $R$ is nilpotent if $a^k = 0$ for some $k ≥ 1$.

Prove that if $a$ is nilpotent, then it is a zero-divisor.

Proof: consider the smallest $k$ such that $a^{k} = 0$. Then 
$a^{k-1} \ne 0$ and $a \cdot a^{k-1} = 0$.

Find an example of a nonzero nilpotent element, in one of the rings $\mathbb{Z}/n\mathbb{Z}$.

Proof: $[2]_8$.

Prove that if a is nilpotent, then 1 + a is invertible.

Proof:

$$
(1 + a) (1 - a) = 1 - a^2 \\
(1 + a) (1 - a + a^2) = 1 + a^3 \\
(1 + a) (1 - a + a^2 - a^3) = 1 - a^4 \\
$$

***3.21*** Let $n > 0$ be an integer and $R = \mathbb{Z}/n\mathbb{Z}$. Prove that every element of $R$ is either
invertible or a zero-divisor. Find a ring $R$ for which this is not true.

Proof. Give $a \in R$, assume $\gcd(a, n) = b > 1$. See exercise 2.17.
Assume $n = br, a = bq$, then $ar = bqr = 0$.

$\gcd(a, n) = b = 1$, so $ab + nr = 1$, so $ab = 1$.

# Appendix

## A.8 Relations; Equivalence Relations and Quotient Sets

* 'Functions' from a set $A$ to a set $B$ are certain subsets of the Cartesian
product $A × B$. More generally, a ‘relation’ between elements of $A$ and elements of $B$ is
any subset $R ⊆ A×B$. We say that $a ∈ A$ and $b ∈ B$ are ‘related by $R$’ if $(a, b) ∈ R$.

* An 'order' relation $R$ satisfies the following three properties. Writing $aRb$ for $(a, b) ∈ R$, we have that $R$ is
  * reflexive, i.e., $aRa$ for every $a ∈ A$;
  * transitive, i.e., $aRb$ and $bRc$ imply $aRc$ for all $a, b, c ∈ A$;
  * antisymmetric, i.e., $aRb$ and $bRa$ imply $a = b$, for all $a, b ∈ A$.

***Example A.19*** The ordinary relation $≤$ on $Z$ is an order relation.

* Of paramount importance in many constructions is the notion of equivalence relation.
A relation $∼$ on a set $A$ is an ‘equivalence relation’ when it is reflexive, symmetric, and transitive, that is:
  * $\forall a \in A, a \sim a$
  * $\forall a, b \in A, a \sim b \implies b \sim a$
  * $\forall a, b, c \in A, a \sim b \wedge b \sim c \implies a \sim c$.

***Example A.20***  The ‘equality’ relation $=$ is an equivalence relation, on any set $A$.

***Example A.21*** Another example may be given by letting $A = Z$ and defining $a \sim b$ to mean that $b − a$ is even.

* If a set $A$ is endowed with an equivalence relation $\sim$, we can define an associated set $A/\sim$, which we call the ‘quotient of $A$ modulo ∼’.
  * This is a prototype for all the ‘quotient’ constructions for rings, 
  modules, groups, that are among the most important
  notions developed in this text.
* The elements of this set are the ‘equivalence classes’ of
the elements of A ‘modulo ∼’, defined by

$$
[a]_{\sim} = \{b \in A  | b \sim a \}
$$

* With this notation, we define

$$
A / \sim = \{[a]_{\sim} | a \in A\}
$$

***Example A.22*** Consider the equivalence relation defined on $\mathbb{Z}$ in Example A.21, by
setting $a \sim b$ if and only if $b − a$ is even. The equivalence class of $0$ is

$$
[0]_{\sim} = \{b \in \mathbb{Z}  | n - 0 \text{ is even } \} \\
[1]_{\sim} = \{b \in \mathbb{Z}  | n - 1 \text{ is even } \} 
$$

* Using the terminology introduced above, the quotient set $Z/\sim$ consists of just two
elements. Notice that the corresponding two subsets of $\mathbb{Z}$ (that is, the set of even integers
and the set of odd integers) are not empty, they are disjoint, and their union is $\mathbb{Z}$.

* It is easy to
verify that the equivalence classes modulo an equivalence relation ∼ on a set $A$ always
form a ‘partition’ of $A$: this means that the equivalence classes are
  * nonempty
  * disjoint
  * their union is the whole set $A$.

* Conversely, if $\mathcal{P}$ is a partition of a set $A$, that is, a collection of subsets of $A$ satisfy-
ing the conditions listed in the previous paragraph, then we can define an equivalence relation $\sim_\mathcal{P}$ on $A$ by setting

$$
a \sim_\mathcal{P} b \iff
\text{a and b belong to the same element of } \mathcal{P}
$$

* if the partition $\mathcal{P}$ arises
from an equivalence relation ∼, i.e., it equals the quotient $A/\sim$, then

$$
a \sim_\mathcal{P} b \iff [a]_∼ = [b]_∼ \iff a ∼ b :
$$

* that is, the equivalence relation $\sim_\mathcal{P}$ corresponding to this partition is nothing but the
equivalence relation ∼ we started from.

# Humor in this book

## section 3.3

Most of the examples we will use in this text will be commutative,
mostly because I earn a living by (teaching and) doing research in algebraic geometry.